gnome-terminal -x bash -c 'iex --sname aa -S mix init_db'
gnome-terminal -x bash -c 'iex --sname bb -S mix init_db'
gnome-terminal -x bash -c 'iex --sname cc -S mix init_db'
gnome-terminal -x bash -c 'iex --sname dd -S mix init_db'
gnome-terminal -x bash -c 'iex --sname ee -S mix init_db'
gnome-terminal -x bash -c 'iex --sname ff -S mix init_db'
gnome-terminal -x bash -c 'iex --sname gg -S mix init_db'
gnome-terminal -x bash -c 'iex --sname hh -S mix init_db'
gnome-terminal -x bash -c 'iex --sname ii -S mix init_db'
iex -S mix init_db