defmodule Hitb.Stat.Repo.Migrations.CreateStatDrg do
  use Ecto.Migration

  def change do
    create table(:stat_drg) do
      add :time, :string #时间
      add :org, :string #机构
      add :true_org, :string #机构
      add :drg, :string #DRG
      add :drg2, :string #DRG
      add :name, :string #名称
      add :num_sum, :integer #病历数
      add :death_num, :integer #死亡人数
      add :death_rate, :float #死亡率
      add :death_rate_log, :float #死亡率对数
      add :icd10_num, :integer #icd10病历数
      add :day_avg, :float #平均住院日
      add :fee_avg, :float
      add :weight_count, :float
      add :fee_index, :float
      add :day_index, :float
      add :cmi, :float
      add :death_age_avg, :float #平均死亡年龄
      add :weight, :float #权重
      add :death_level, :string #死亡风险等级
      add :time_type, :string #时间维度
      add :org_type, :string #机构维度
      add :etype, :string #病种维度
      add :mdc_code, :string #mdc编码
      add :int_time, :integer #时间排序

      add :zdxg_num, :integer #诊断相关组数
      add :wlzl_num, :integer #临床物理治疗病历数
      add :jrzl_num, :integer #介入治疗病历数
      add :tszl_num, :integer #特殊治疗病历数
      add :kfzl_num, :integer #康复治疗病历数
      add :zyzl_num, :integer #中医治疗病历数
      add :ybzl_num, :integer #一般治疗病历数
      add :jszl_num, :integer #精神治疗病历数
      add :wlzl_rate, :float #临床物理治疗占比
      add :jrzl_rate, :float #介入治疗占比
      add :tszl_rate, :float #特殊治疗占比
      add :kfzl_rate, :float #康复治疗占比
      add :zyzl_rate, :float #中医治疗占比
      add :ybzl_rate, :float #一般治疗占比
      add :jszl_rate, :float #精神治疗占比
      add :ccu_num, :integer #心脏监护室（CCU）总人数
      add :ricu_num, :integer #呼吸监护室（RICU）总人数
      add :sicu_num, :integer #外科监护室（SICU）总人数
      add :nicu_num, :integer #新生儿监护室（NICU）总人数
      add :picu_num, :integer #儿科监护室（PICU）总人数
      add :other_num, :integer #其他监护室总人数
      add :ccu_rate, :float #心脏监护室（CCU）总人数占比
      add :ricu_rate, :float #呼吸监护室（RICU）总人数占比
      add :sicu_rate, :float #外科监护室（SICU）总人数占比
      add :nicu_rate, :float #新生儿监护室（NICU）总人数占比
      add :picu_rate, :float #儿科监护室（PICU）总人数占比
      add :other_rate, :float #其他监护室总人数占比
      add :sjkfzc_num, :integer #实际开放总床日数
      add :sjzyzc_num, :integer #实际占用总床日数
      add :cyzzyzc_num, :integer #出院者占用总床日数
      add :pjkfbc_num, :integer #平均开放病床数
      add :bczz_num, :integer #病床周转次数
      add :bcgzr_num, :integer #病床工作日
      add :cyzpjzy_num, :integer #出院者平均住院日
      add :bcsy_rate, :float #病床使用率
      add :ylsy_num, :integer #医疗使用病历数
      add :zl_num, :integer #诊疗病历数
      add :zl_rate, :float #诊疗占比
      add :jc_num, :integer #一般检查病历数
      add :jc_rate, :float #一般检查占比
      add :js_num, :integer #接生病历数
      add :js_rate, :float #接生占比
      add :yjsy_num, :integer #医技使用病历数
      add :hsjc_num, :integer #核素检查病历数
      add :hszl_num, :integer #核素治疗病历数
      add :cszl_num, :integer #超声治疗病历数
      add :fszl_num, :integer #放射治疗病历数
      add :hy_num, :integer #化验病历数
      add :bl_num, :integer #病理病历数
      add :yjsy_rate, :float #医技使用病历数占比
      add :hsjc_rate, :float #核素检查占比
      add :hszl_rate, :float #核素治疗占比
      add :cszl_rate, :float #超声治疗占比
      add :fszl_rate, :float #放射治疗占比
      add :hy_rate, :float #化验占比
      add :bl_rate, :float #病理检验占比
      add :hsjc_expense, :float #核素检查费
      add :hszl_expense, :float #核素治疗费
      add :cs_expense, :float #超声费
      add :fs_expense, :float #放射费
      add :hy_expense, :float #化验费
      add :bl_expense, :float #病理费
      add :avg_hsjc, :float #例均核素检查费
      add :avg_hszl, :float #例均核素治疗费
      add :avg_cs, :float #例均超声费
      add :avg_fs, :float #例均放射费
      add :avg_hy, :float #例均化验费
      add :avg_bl, :float #例均病理费
      # add :hsjc_rate, :float #核素检查费占比
      # add :hszl_rate, :float #核素治疗费占比
      add :csf_rate, :float #超声费占比
      add :fsf_rate, :float #放射费占比
      add :hyf_rate, :float #化验费占比
      add :blf_rate, :float #病理费占比
      add :jhfz_num, :integer #监护及辅助病历数
      add :jhfz_rate, :float #监护及辅助占比
      add :sx_num, :integer #输血病历数
      add :sx_rate, :float #输血占比
      add :sy_num, :integer #输氧使用病历数
      add :sy_rate, :float #输氧人数占比
      add :dfx_num, :integer #低风险组病历数
      add :dfxsw_num, :integer #低风险组死亡人数
      add :dfxsw_rate, :float #低风险组死亡率
      add :dfx_age, :float #低风险平均死亡年龄
      add :ysj_num, :integer #低风险组有尸检病历数
      add :wsj_num, :integer #低风险组无尸检病历数
      add :zdfx_num, :integer #中低风险组病历数
      add :zdfxsw_num, :integer #中低风险组死亡人数
      add :zdfxsw_rate, :float #中低风险组死亡率
      add :zdfx_age, :float #中低风险平均死亡年龄
      add :zdysj_num, :integer #中低风险组有尸检病历数
      add :zdwsj_num, :integer #中低风险组无尸检病历数
      add :zgfx_num, :integer #中高风险组病历数
      add :zgfxsw_num, :integer #中高风险组死亡人数
      add :zgfxsw_rate, :float #中高风险组死亡率
      add :zgfx_age, :float #中高风险平均死亡年龄
      add :zgysj_num, :integer #中高风险组有尸检病历数
      add :zgwsj_num, :integer #中高风险组无尸检病历数
      add :gfx_num, :integer #高风险组病历数
      add :gfxsw_num, :integer #高风险组死亡人数
      add :gfxsw_rate, :float #高风险组死亡率
      add :gfx_age, :float #高风险组死亡年龄
      add :gysj_num, :integer #高风险组有尸检病历数
      add :gwsj_num, :integer #高风险组无尸检病历数
      add :yl_expense, :float #医疗总费用
      add :zl_expense, :float #诊察（诊疗）费
      add :ybjc_expense, :float #一般检查费
      add :js_expense, :float #接生费
      add :mz_expense, :float #麻醉费
      add :ss_expense, :float #手术费
      add :avg_yl, :float #例均医疗费用
      add :avg_zl, :float #例均诊察(诊疗)费
      add :avg_ybjc, :float #例均一般检查费
      add :avg_js, :float #例均接生费
      add :avg_mz, :float #例均麻醉费
      add :avg_ss, :float #例均手术费
      add :yl_rate, :float #医疗费用占比
      add :zlf_rate, :float #诊察（诊疗）费占比
      add :ybjcf_rate, :float #一般检查费占比
      add :jsf_rate, :float #接生费占比
      add :mzf_rate, :float #麻醉费占比
      add :ssf_rate, :float #手术费占比
      add :jrzl_expense, :float #介入治疗费
      add :tszl_expense, :float #特殊治疗费
      add :kfzl_expense, :float #康复治疗费
      add :zyzl_expense, :float #中医治疗费
      add :ybzl_expense, :float #一般治疗费
      add :jszl_expense, :float #精神治疗费
      add :wlzl_expense, :float #临床物理治疗费
      add :avg_jrzl, :float #例均介入治疗费
      add :avg_tszl, :float #例均特殊治疗费
      add :avg_kfzl, :float #例均康复治疗费
      add :avg_zyzl, :float #例均中医治疗费
      add :avg_ybzl, :float #例均一般治疗费
      add :avg_jszl, :float #例均精神治疗费
      add :avg_wlzl, :float #例均临床物理治疗费
      add :jrzlf_rate, :float #介入治疗费占比
      add :tszlf_rate, :float #特殊治疗费占比
      add :kfzlf_rate, :float #康复治疗费占比
      add :zyzlf_rate, :float #中医治疗费占比
      add :ybzlf_rate, :float #一般治疗费占比
      add :jszlf_rate, :float #精神治疗费占比
      add :wlzlf_rate, :float #临床物理治疗费占比
      add :glze_expense, :float #管理总额
      add :jhfz_expense, :float #监护及辅助呼吸费
      add :cw_expense, :float #床位费
      add :gh_expense, :float #挂号费
      add :sy_expense, :float #输氧费
      add :other_expense, :float #其他费用
      add :avg_glze, :float #例均管理总额
      add :avg_jhfz, :float #例均监护及辅助呼吸费
      add :avg_cw, :float #例均床位费
      add :avg_gh, :float #例均挂号费
      add :avg_sy, :float #例均输氧费
      add :avg_other, :float #例均其他费用
      add :glze_rate, :float #管理总额占比
      add :jhfzf_rate, :float #监护及辅助呼吸费占比
      add :cwf_rate, :float #床位费占比
      add :ghf_rate, :float #挂号费占比
      add :syf_rate, :float #输氧费占比
      add :otherf_rate, :float #其他费用占比
      add :zc_expense, :float #中成药费
      add :zcy_expense, :float #中草药费
      add :avg_zc, :float #例均中成药费
      add :avg_zcy, :float #例均中草药费
      add :zc_rate, :float #中成药费占比
      add :zcy_rate, :float #中草药费占比
      add :hlze_num, :integer #护理总额
      add :hlzl_num, :integer #护理治疗费
      add :hlf_num, :integer #护理费
      add :hlzl_avg, :float #例均护理总额
      add :hlf_avg, :float #例均护理治疗费
      add :hlze_rate, :float #护理总额占比
      add :hlzl_rate, :float #护理治疗费占比
      add :hlf_rate, :float #护理费占比
      add :sx_expense, :float #输血费
      add :xy_expense, :float #西药费
      add :kjy_expense, :float #抗菌药物费
      add :bdb_expense, :float #白蛋白类制品费
      add :qdb_expense, :float #球蛋白类制品费
      add :nxyz_expense, :float #凝血因子类制品费
      add :xbyz_expense, :float #细胞因子类制品费
      add :avg_sxf, :float #例均输血费
      add :avg_xyf, :float #例均西药费
      add :avg_kjy, :float #例均抗菌药物费
      add :avg_bdb, :float #例均白蛋白类制品费
      add :avg_qdb, :float #例均球蛋白类制品费
      add :avg_nxyz, :float #例均凝血因子类制品费
      add :avg_xbyz, :float #例均细胞因子类制品费
      add :sxf_rate, :float #输血费占比
      add :xyf_rate, :float #西药费占比
      add :kjy_rate, :float #抗菌药物费占比
      add :bdb_rate, :float #白蛋白类制品费占比
      add :qdb_rate, :float #球蛋白类制品费占比
      add :nxyz_rate, :float #凝血因子类制品费占比
      add :xbyz_rate, :float #细胞因子类制品费占比
      add :ypzef, :float #药品总额
      add :zlyc_expense, :float #治疗用一次性医用材料费
      add :jryc_expense, :float #介入用一次性医用材料费
      add :ssyc_expense, :float #手术用一次性医用材料费
      add :jcyc_expense, :float #检查用一次性医用材料费
      add :hc_expense, :float #耗材成本
      add :avg_yp, :float #例均药品费用
      add :avg_zlyc, :float #例均治疗用一次性医用材料费
      add :avg_jryc, :float #例均介入用一次性医用材料费
      add :avg_ssyc, :float #例均手术用一次性医用材料费
      add :avg_jcyc, :float #例均检查用一次性医用材料费
      add :avg_hc, :float #例均耗材成本
      add :yp_rate, :float #药品总额占比
      add :zlyc_rate, :float #治疗用一次性医用材料费占比
      add :jryc_rate, :float #介入用一次性医用材料费占比
      add :ssyc_rate, :float #手术用一次性医用材料费占比
      add :jcyc_rate, :float #检查用一次性医用材料费占比
      add :hc_rate, :float #耗材成本率
      add :is_inhosp31, :integer #有出院31日再入院计划患者数
      add :inhosp_rate, :float #再住院计划患者率
      add :num_num1, :integer #出院当天再入院人数
      add :num_rate1, :float #出院当天再入院率
      add :num_num2, :integer #2-15再入院人数
      add :num_rate2, :float #2-15再入院率
      add :num_num3, :integer #16-31再入院人数
      add :num_rate3, :float #16-31再入院人率
      add :yzly_num, :integer #医嘱离院患者总人数
      add :yzly_rate, :float #医嘱离院率
      add :yzzy_num, :integer #医嘱转院患者总人数
      add :yzzy_rate, :float #医嘱转院率
      add :yzzsq_num, :integer #医嘱转社区卫生服务机构/乡镇卫生院患者总人数
      add :yzzsq_rate, :float #医嘱转社区率
      add :fyzly_num, :integer #非医嘱离院患者总人数
      add :fyzly_rate, :float #非医嘱离院率
      add :rycyfh_num, :integer #入院诊断与出院诊断符合人数
      add :rycyfh_rate, :float #入院诊断与出院诊断符合率
      add :zdblfh_num, :integer #诊断与病理诊断符合人数
      add :zdblfh_rate, :float #诊断与病理诊断符合率
      add :ryssfh_num, :integer #入院诊断与手术诊断符合人数
      add :ryssfh_rate, :float #入院诊断与手术诊断符合率
      add :hlfxsj_num, :integer #护理负性事件患者总数
      add :syyw_num, :integer #输液意外损伤人数
      add :syyl_num, :integer #输液遗留体内异物人数
      add :syyf_num, :integer #输液无菌预防措施的失败人数
      add :syry_num, :integer #输液时溶液稀释不当人数
      add :sywr_num, :integer #输液器械的污染人数
      add :sygl_num, :integer #输液液体过量人数
      add :hlfxsj_rate, :float #护理负性事件患者总数占比
      add :syyw_rate, :float #输液意外损伤人数占比
      add :syyl_rate, :float #输液遗留体内异物人数占比
      add :syyf_rate, :float #输液无菌预防措施的失败人数占比
      add :syry_rate, :float #输液时溶液稀释不当人数占比
      add :sywr_rate, :float #输液器械的污染人数占比
      add :sygl_rate, :float #输液液体过量人数占比
      add :sxfxsj_num, :integer #输血负性事件患者总数
      add :sxyw_num, :integer #输血意外损伤人数
      add :sxyl_num, :integer #输血遗留体内异物人数
      add :sxyf_num, :integer #输血无菌预防措施的失败人数
      add :sxwr_num, :integer #输血器械的污染人数
      add :sxgl_num, :integer #输血液体过量人数
      add :sxfxsj_rate, :float #输血负性事件患者总数占比
      add :sxyw_rate, :float #输血意外损伤人数占比
      add :sxyl_rate, :float #输血遗留体内异物人数占比
      add :sxyf_rate, :float #输血无菌预防措施的失败人数占比
      add :sxwr_rate, :float #输血器械的污染人数占比
      add :sxgl_rate, :float #输血液体过量人数占比
      add :ychz_num, :integer #压疮患者总数
      add :odyc_num, :integer #Ⅰ度压疮患者数
      add :wdyc_num, :integer #Ⅱ度压疮患者数
      add :tdyc_num, :integer #Ⅲ度压疮患者数
      add :fdyc_num, :integer #Ⅳ度压疮患者数
      add :ychz_rate, :float #压疮患者总数占比
      add :odyc_rate, :float #Ⅰ度压疮患者占比
      add :wdyc_rate, :float #Ⅱ度压疮患者占比
      add :tdyc_rate, :float #Ⅲ度压疮患者占比
      add :fdyc_rate, :float #Ⅳ度压疮患者占比
      add :ywdd_num, :integer #意外跌倒患者总数
      add :ycdd_rate, :float #意外跌倒患者总数占比
      add :zc_num, :integer #坠床患者总数
      # add :zc_rate, :float #坠床患者总数占比
      add :ywfxsj_num, :integer #药物负性事件患者总数
      add :ywfxsj_rate, :float #药物负性事件患者总数占比
      add :ywgl_num, :integer #药物过量人数
      add :ywgl_rate, :float #药物过量占比
      add :ywgc_num, :integer #药物给错总人数
      add :ywgc_rate, :float #药物给错总人数占比
      add :sqday_num, :integer #术前平均住院日
      add :shday_num, :integer #术后平均住院日
      add :fjh_num, :integer #非计划再次手术例数
      add :fjh_rate, :float #非计划再次手术例数占比
      add :zdss_num, :integer #重点手术例数
      add :sw_num, :integer #死亡例数
      add :sw_rate, :float #死亡例数占比
      add :qklk_num, :integer #切口裂开患者总人数
      add :qklk_rate, :float #切口裂开患者总人数占比
      add :qkgr_num, :integer #切口感染患者总人数
      add :qkgr_rate, :float #切口感染率总人数占比
      add :shgr_num, :integer #术后感染例数
      add :shgr_rate, :float #术后感染例数占比
      add :shbf_num, :integer #术后并发症例数
      add :shbf_rate, :float #术后并发症例数占比
      add :yjqk_num, :integer #Ⅰ/甲切口愈合等级患者总人数
      add :yjqk_rate, :float #Ⅰ/甲切口愈合等级患者总人数占比
      add :ejqk_num, :integer #Ⅱ/甲切切口愈合等级患者总人数
      add :ejqk_rate, :float #Ⅱ/甲切切口愈合等级患者总人数占比
      add :sjqk_num, :integer #Ⅲ/甲切口愈合等级患者总人数
      add :sjqk_rate, :float #Ⅲ/甲切口愈合等级患者总人数占比
      add :yss_num, :integer #有手术，但体表无切口患者总人数
      add :yss_rate, :float #有手术，但体表无切口患者人数占比
      add :yjqtqk_num, :integer #Ⅰ/其他切口愈合等级患者总人数
      add :yjqtqk_rate, :float #Ⅰ/其他切口愈合等级患者总人数占比
      add :ejqtqk_num, :integer #Ⅱ/其他切口愈合等级患者总人数
      add :ejqtqk_rate, :float #Ⅱ/其他切口愈合等级患者总人数占比
      add :sjqtqk_num, :integer #Ⅲ/其他切口愈合等级患者总人数
      add :sjqtqk_rate, :float #Ⅲ/其他切口愈合等级患者总人数占比
      add :yjyqk_num, :integer #Ⅰ/乙切口愈合等级患者总人数
      add :yjyqk_rate, :float #Ⅰ/乙切口愈合等级患者总人数占比
      add :ejyqk_num, :integer #Ⅱ/乙切切口愈合等级患者总人数
      add :ejyqk_rate, :float #Ⅱ/乙切切口愈合等级患者总人数占比
      add :sjyqk_num, :integer #Ⅲ/乙切口愈合等级患者总人数
      add :sjyqk_rate, :float #Ⅲ/乙切口愈合等级患者总人数占比
      add :yjbqk_num, :integer #Ⅰ/丙切口愈合等级患者总人数
      add :yjbqk_rate, :float #Ⅰ/丙切口愈合等级患者总人数占比
      add :ejbqk_num, :integer #Ⅱ/丙切口愈合等级患者总人数
      add :ejbqk_rate, :float #Ⅱ/丙切口愈合等级患者总人数占比
      add :sjbqk_num, :integer #Ⅲ/丙切口愈合等级患者总人数
      add :sjbqk_rate, :float #Ⅲ/丙切口愈合等级患者总人数占比
      add :ojss_num, :integer #一级手术患者总人数
      add :ojss_rate, :float #一级手术患者总人数占比
      add :wjss_num, :integer #二级手术患者总人数
      add :wjss_rate, :float #二级手术患者总人数占比
      add :tjss_num, :integer #三级手术患者总人数
      add :tjss_rate, :float #三级手术患者总人数占比
      add :fjss_num, :integer #四级手术患者总人数
      add :fjss_rate, :float #四级手术患者总人数占比
      add :bazlj_num, :integer #病案质量为甲级病案总数
      add :bazlj_rate, :float #病案质量为甲级病案总数占比
      add :bazly_num, :integer #病案质量为乙级病案总数
      add :bazly_rate, :float #病案质量为乙级病案总数占比
      add :bazlb_num, :integer #病案质量为丙级病案总数
      add :bazlb_rate, :float #病案质量为丙级病案总数占比
      add :tl_num, :integer #肿瘤患者T0期总人数
      add :to_num, :integer #肿瘤患者T1期总人数
      add :tw_num, :integer #肿瘤患者T2期总人数
      add :tt_num, :integer #肿瘤患者T3期总人数
      add :tf_num, :integer #肿瘤患者T4期总人数
      add :wfpgyf_num, :integer #肿瘤患者无法评估原发肿瘤大小总人数
      add :tl_rate, :float #肿瘤患者T0期总人数占比
      add :to_rate, :float #肿瘤患者T1期总人数占比
      add :tw_rate, :float #肿瘤患者T2期总人数占比
      add :tt_rate, :float #肿瘤患者T3期总人数占比
      add :tf_rate, :float #肿瘤患者T4期总人数占比
      add :wfpgyf_rate, :float #肿瘤患者无法评估原发肿瘤大小总人数占比
      add :nl_num, :integer #肿瘤患者N0期总人数
      add :no_num, :integer #肿瘤患者N1期总人数
      add :nw_num, :integer #肿瘤患者N2期总人数
      add :nt_num, :integer #肿瘤患者N3期总人数
      add :nf_num, :integer #肿瘤患者N4期总人数
      add :wfpglb_num, :integer #肿瘤患者无法评估区域淋巴结有无转移总人数
      add :nl_rate, :float #肿瘤患者N0期总人数占比
      add :no_rate, :float #肿瘤患者N1期总人数占比
      add :nw_rate, :float #肿瘤患者N2期总人数占比
      add :nt_rate, :float #肿瘤患者N3期总人数占比
      add :nf_rate, :float #肿瘤患者N4期总人数占比
      add :wfpglb_rate, :float #肿瘤患者无法评估区域淋巴结有无转移总人数占比
      add :ml_num, :integer #肿瘤患者M0期总人数
      add :ml_rate, :float #肿瘤患者M0期总人数占比
      add :mo_num, :integer #肿瘤患者M1期总人数
      add :mo_rate, :float #肿瘤患者M1期总人数占比
      add :wfpgyc_num, :integer #肿瘤患者无法评估远处是否转移总人数
      add :wfpgyc_rate, :float #肿瘤患者无法评估远处是否转移总人数占比
      add :man_num, :integer #男性患者
      add :man_rate, :float #男性患者占比
      add :woman_num, :integer #女性患者
      add :woman_rate, :float #女性患者占比
      add :bd_num, :integer #本地患者数
      add :bd_rate, :float #本地患者数占比
      add :wd_num, :integer #外地患者数
      add :wd_rate, :float #外地患者数占比
      add :xhxt_num, :integer #消化系统总人数
      add :sjxt_num, :integer #神经系统总人数
      add :hxxt_num, :integer #呼吸系统总人数
      add :xyxh_num, :integer #血液循环系统总人数
      add :ydxt_num, :integer #运动系统总人数
      add :nfm_num, :integer #内分泌系统总人数
      add :mnxt_num, :integer #泌尿系统总人数
      add :szxt_num, :integer #生殖系统总人数
      add :xhxt_rate, :float #消化系统总人数占比
      add :sjxt_rate, :float #神经系统总人数占比
      add :hxxt_rate, :float #呼吸系统总人数占比
      add :xyxh_rate, :float #血液循环系统总人数占比
      add :ydxt_rate, :float #运动系统总人数占比
      add :nfm_rate, :float #内分泌系统总人数占比
      add :mnxt_rate, :float #泌尿系统总人数占比
      add :szxt_rate, :float #生殖系统总人数占比
      add :zlfq_num, :integer #肿瘤分期不详患者总人数
      add :gfh_num, :integer #高分化程度患者总人数
      add :zfh_num, :integer #中分化程度患者总人数
      add :dfh_num, :integer #低分化程度患者总人数
      add :wfh_num, :integer #未分化程度患者总人数
      add :wqd_num, :integer #未确定程度患者总人数
      add :zlfq_rate, :float #肿瘤分期不详患者总人数占比
      add :gfh_rate, :float #高分化程度患者总人数占比
      add :zfh_rate, :float #中分化程度患者总人数占比
      add :dfh_rate, :float #低分化程度患者总人数占比
      add :wfh_rate, :float #未分化程度患者总人数占比
      add :wqd_rate, :float #未确定程度患者总人数占比
      add :txb_num, :integer #T细胞程度患者总人数
      add :txb_rate, :float #T细胞程度患者总人数占比
      add :bxb_num, :integer #B细胞程度患者总人数
      add :bxb_rate, :float #B细胞程度患者总人数占比
      add :ftfbxb_num, :integer #非T-非B程度患者总人数
      add :ftfbxb_rate, :float #非T-非B程度患者总人数占比
      add :nk_num, :integer #NK（自然杀伤）细胞程度患者总人数
      add :nk_rate, :float #NK（自然杀伤）细胞程度患者总人数占比
      add :lczg_num, :integer #临床诊断作为最高诊断依据患者总人数
      add :xxct_num, :integer #X线、CT、超声波、内窥镜等诊断作为最高诊断依据患者总人数
      add :sszd_num, :integer #手术诊断作为最高诊断依据患者总人数
      add :shmy_num, :integer #生化、免疫诊断作为最高诊断依据患者总人数
      add :xbx_num, :integer #细胞学、血片诊断作为最高诊断依据患者总人数
      add :bljf_num, :integer #病理（继发）诊断作为最高诊断依据患者总人数
      add :blyf_num, :integer #病理（原发）诊断作为最高诊断依据患者总人数
      add :sjybl_num, :integer #尸检（有病理）诊断作为最高诊断依据患者总人数
      add :zgzdyj_num, :integer #最高诊断依据不详患者总人数
      add :lczg_rate, :float #临床诊断作为最高诊断依据患者总人数占比
      add :xxct_rate, :float #X线、CT、超声波、内窥镜等诊断作为最高诊断依据患者总人数占比
      add :sszd_rate, :float #手术诊断作为最高诊断依据患者总人数占比
      add :shmy_rate, :float #生化、免疫诊断作为最高诊断依据患者总人数占比
      add :xbx_rate, :float #细胞学、血片诊断作为最高诊断依据患者总人数占比
      add :bljf_rate, :float #病理（继发）诊断作为最高诊断依据患者总人数占比
      add :blyf_rate, :float #病理（原发）诊断作为最高诊断依据患者总人数占比
      add :sjybl_rate, :float #尸检（有病理）诊断作为最高诊断依据患者总人数占比
      add :zgzdyj_rate, :float #最高诊断依据不详患者总人数占比
      add :rhya_num, :integer #RH阴性_A型血型患者总人数
      add :rhya_rate, :float #RH阴性_A型血型患者总人数占比
      add :rhyb_num, :integer #RH阴性_B型血型患者总人数
      add :rhyb_rate, :float #RH阴性_B型血型患者总人数占比
      add :rhyo_num, :integer #RH阴性_O型血型患者总人数
      add :rhyo_rate, :float #RH阴性_O型血型患者总人数占比
      add :rhyab_num, :integer #RH阴性_AB型血型患者总人数
      add :rhyab_rate, :float #RH阴性_AB型血型患者总人数占比
      add :rhbxa_num, :integer #RH不详_A型血型患者总人数
      add :rhbxa_rate, :float #RH不详_A型血型患者总人数占比
      add :rhbxb_num, :integer #RH不详_B型血型患者总人数
      add :rhbxb_rate, :float #RH不详_B型血型患者总人数占比
      add :rhbxo_num, :integer #RH不详_O型血型患者总人数
      add :rhbxo_rate, :float #RH不详_O型血型患者总人数占比
      add :rhbxab_num, :integer #RH不详_AB型血型患者总人数
      add :rhbxab_rate, :float #RH不详_AB型血型患者总人数占比
      add :rhyxa_num, :integer #RH阳性_A型血型患者总人数
      add :rhyxa_rate, :float #RH阳性_A型血型患者总人数占比
      add :rhyxb_num, :integer #RH阳性_B型血型患者总人数
      add :rhyxb_rate, :float #RH阳性_B型血型患者总人数占比
      add :rhyxo_num, :integer #RH阳性_O型血型患者总人数
      add :rhyxo_rate, :float #RH阳性_O型血型患者总人数占比
      add :rhyxab_num, :integer #RH阳性_AB型血型患者总人数
      add :rhyxab_rate, :float #RH阳性_AB型血型患者总人数占比
      add :rhyxa_cc, :integer #Rh阳性_A型血型使用总单位数
      add :rhyxb_cc, :integer #Rh阳性_B型血型使用总单位数
      add :rhyxab_cc, :integer #Rh阳性_AB型血型使用总单位数
      add :rhyxo_cc, :integer #Rh阳性_O型血型使用总单位数
      add :rhyxacc_rate, :float #Rh阳性_A型血型使用总单位数占比
      add :rhyxbcc_rate, :float #Rh阳性_B型血型使用总单位数占比
      add :rhyxabcc_rate, :float #Rh阳性_AB型血型使用总单位数占比
      add :rhyx0cc_rate, :float #Rh阳性_O型血型使用总单位数占比
      add :rhyacc_rate, :float #Rh阴性_A型血型使用总单位数占比
      add :rhybcc_rate, :float #Rh阴性_B型血型使用总单位数占比
      add :rhyabcc_rate, :float #Rh阴性_AB型血型使用总单位数占比
      add :rhy0cc_rate, :float #Rh阴性_O型血型使用总单位数占比
      add :rhya_cc, :integer #Rh阴性_A型血型使用总单位数
      add :rhyb_cc, :integer #Rh阴性_B型血型使用总单位数
      add :rhyab_cc, :integer #Rh阴性_AB型血型使用总单位数
      add :rhyo_cc, :integer #Rh阴性_O型血型使用总单位数
      add :cfx_num, :integer #成分血总单位数
      add :hxb_num, :integer #红细胞使用总单位数
      add :xsb_num, :integer #血小板使用总单位数
      add :xj_num, :integer #血浆使用总单位数
      add :qx_num, :integer #全血使用总单位数
      add :qtx_num, :integer #其它血制品使用总单位数
      add :cfx_avg, :float #例均成分血使用总单位数
      add :hxb_avg, :float #例均红细胞使用总单位数
      add :xsb_avg, :float #例均血小板使用总单位数
      add :xj_avg, :float #例均血浆使用总单位数
      add :qx_avg, :float #例均全血使用总单位数
      add :qtx_avg, :float #例均其它血制品使用总单位数
      add :cfx_rate, :float #成分血总单位数占比
      add :hxb_rate, :float #红细胞使用总单位数占比
      add :xsb_rate, :float #血小板使用总单位数占比
      add :xj_rate, :float #血浆使用总单位数占比
      add :qx_rate, :float #全血使用总单位数占比
      add :qtx_rate, :float #其它血制品使用总单位数占比
      add :bszg_num, :integer #本市城镇职工基本医疗保险患者支付总额
      add :bszgzf_num, :integer #本市城镇职工基本医疗保险患者自付总额
      add :bszgyl_num, :integer #本市城镇职工基本医疗保险患者医疗总额
      add :bszgyj_num, :integer #本市城镇职工基本医疗保险患者医技总额
      add :bszgypj_num, :integer #本市城镇职工基本医疗保险患者药品总额
      add :bszghl_num, :integer #本市城镇职工基本医疗保险患者护理总额
      add :bszggl_num, :integer #本市城镇职工基本医疗保险患者管理总额
      add :bszg_avg, :float #本市城镇职工基本医疗保险患者例均支付总额
      add :bszgzf_avg, :float #本市城镇职工基本医疗保险患者例均自付总额
      add :bszgyl_avg, :float #本市城镇职工基本医疗保险患者例均医疗总额
      add :bszgyj_avg, :float #本市城镇职工基本医疗保险患者例均医技总额
      add :bszgypj_avg, :float #本市城镇职工基本医疗保险患者例均药品总额
      add :bszghl_avg, :float #本市城镇职工基本医疗保险患者例均护理总额
      add :bszggl_avg, :float #本市城镇职工基本医疗保险患者例均管理总额
      add :bszg_rate, :float #本市城镇职工基本医疗保险患者支付总额占比
      add :bszgzf_rate, :float #本市城镇职工基本医疗保险患者自付总额占比
      add :bszgyl_rate, :float #本市城镇职工基本医疗保险患者医疗总额占比
      add :bszgyj_rate, :float #本市城镇职工基本医疗保险患者医技总额占比
      add :bszgypj_rate, :float #本市城镇职工基本医疗保险患者药品总额占比
      add :bszghl_rate, :float #本市城镇职工基本医疗保险患者护理总额占比
      add :bszggl_rate, :float #本市城镇职工基本医疗保险患者管理总额占比
      add :wbzg_num, :integer #外埠城镇职工基本医疗保险患者支付总额
      add :wbzgzf_num, :integer #外埠城镇职工基本医疗保险患者自付总额
      add :wbzgyl_num, :integer #外埠城镇职工基本医疗保险患者医疗总额
      add :wbzgyj_num, :integer #外埠城镇职工基本医疗保险患者医技总额
      add :wbzgypj_num, :integer #外埠城镇职工基本医疗保险患者药品总额
      add :wbzghl_num, :integer #外埠城镇职工基本医疗保险患者护理总额
      add :wbzggl_num, :integer #外埠城镇职工基本医疗保险患者管理总额
      add :wbzg_avg, :float #外埠城镇职工基本医疗保险患者例均支付总额
      add :wbzgzf_avg, :float #外埠城镇职工基本医疗保险患者例均自付总额
      add :wbzgyl_avg, :float #外埠城镇职工基本医疗保险患者例均医疗总额
      add :wbzgyj_avg, :float #外埠城镇职工基本医疗保险患者例均医技总额
      add :wbzgypj_avg, :float #外埠城镇职工基本医疗保险患者例均药品总额
      add :wbzghl_avg, :float #外埠城镇职工基本医疗保险患者例均护理总额
      add :wbzggl_avg, :float #外埠城镇职工基本医疗保险患者例均管理总额
      add :wbzg_rate, :float #外埠城镇职工基本医疗保险患者支付总额占比
      add :wbzgzf_rate, :float #外埠城镇职工基本医疗保险患者自付总额占比
      add :wbzgyl_rate, :float #外埠城镇职工基本医疗保险患者医疗总额占比
      add :wbzgyj_rate, :float #外埠城镇职工基本医疗保险患者医技总额占比
      add :wbzgypj_rate, :float #外埠城镇职工基本医疗保险患者药品总额占比
      add :wbzghl_rate, :float #外埠城镇职工基本医疗保险患者护理总额占比
      add :wbzggl_rate, :float #外埠城镇职工基本医疗保险患者管理总额占比
      add :bsjm_num, :integer #本市城镇居民基本医疗保险患者支付总额
      add :bsjmzf_num, :integer #本市城镇居民基本医疗保险患者自付总额
      add :bsjmyl_num, :integer #本市城镇居民基本医疗保险患者医疗总额
      add :bsjmyj_num, :integer #本市城镇居民基本医疗保险患者医技总额
      add :bsjmypj_num, :integer #本市城镇居民基本医疗保险患者药品总额
      add :bsjmhl_num, :integer #本市城镇居民基本医疗保险患者护理总额
      add :bsjmgl_num, :integer #本市城镇居民基本医疗保险患者管理总额
      add :bsjm_avg, :float #本市城镇居民基本医疗保险患者例均支付总额
      add :bsjmzf_avg, :float #本市城镇居民基本医疗保险患者例均自付总额
      add :bsjmyl_avg, :float #本市城镇居民基本医疗保险患者例均医疗总额
      add :bsjmyj_avg, :float #本市城镇居民基本医疗保险患者例均医技总额
      add :bsjmypj_avg, :float #本市城镇居民基本医疗保险患者例均药品总额
      add :bsjmhl_avg, :float #本市城镇居民基本医疗保险患者例均护理总额
      add :bsjmgl_avg, :float #本市城镇居民基本医疗保险患者例均管理总额
      add :bsjm_rate, :float #本市城镇居民基本医疗保险患者支付总额占比
      add :bsjmzf_rate, :float #本市城镇居民基本医疗保险患者自付总额占比
      add :bsjmyl_rate, :float #本市城镇居民基本医疗保险患者医疗总额占比
      add :bsjmyj_rate, :float #本市城镇居民基本医疗保险患者医技总额占比
      add :bsjmypj_rate, :float #本市城镇居民基本医疗保险患者药品总额占比
      add :bsjmhl_rate, :float #本市城镇居民基本医疗保险患者护理总额占比
      add :bsjmgl_rate, :float #本市城镇居民基本医疗保险患者管理总额占比
      add :wbjm_num, :integer #外埠城镇居民基本医疗保险患者支付总额
      add :wbjmzf_num, :integer #外埠城镇居民基本医疗保险患者自付总额
      add :wbjmyl_num, :integer #外埠城镇居民基本医疗保险患者医疗总额
      add :wbjmyj_num, :integer #外埠城镇居民基本医疗保险患者医技总额
      add :wbjmypj_num, :integer #外埠城镇居民基本医疗保险患者药品总额
      add :wbjmhl_num, :integer #外埠城镇居民基本医疗保险患者护理总额
      add :wbjmgl_num, :integer #外埠城镇居民基本医疗保险患者管理总额
      add :wbjm_avg, :float #外埠城镇居民基本医疗保险患者例均支付总额
      add :wbjmzf_avg, :float #外埠城镇居民基本医疗保险患者例均自付总额
      add :wbjmyl_avg, :float #外埠城镇居民基本医疗保险患者例均医疗总额
      add :wbjmyj_avg, :float #外埠城镇居民基本医疗保险患者例均医技总额
      add :wbjmypj_avg, :float #外埠城镇居民基本医疗保险患者例均药品总额
      add :wbjmhl_avg, :float #外埠城镇居民基本医疗保险患者例均护理总额
      add :wbjmgl_avg, :float #外埠城镇居民基本医疗保险患者例均管理总额
      add :wbjm_rate, :float #外埠城镇居民基本医疗保险患者支付总额占比
      add :wbjmzf_rate, :float #外埠城镇居民基本医疗保险患者自付总额占比
      add :wbjmyl_rate, :float #外埠城镇居民基本医疗保险患者医疗总额占比
      add :wbjmyj_rate, :float #外埠城镇居民基本医疗保险患者医技总额占比
      add :wbjmypj_rate, :float #外埠城镇居民基本医疗保险患者药品总额占比
      add :wbjmhl_rate, :float #外埠城镇居民基本医疗保险患者护理总额占比
      add :wbjmgl_rate, :float #外埠城镇居民基本医疗保险患者管理总额占比
      add :bsxnh_num, :integer #本市新型农村合作医疗患者支付总额
      add :bsxnhzf_num, :integer #本市新型农村合作医疗患者自付总额
      add :bsxnhyl_num, :integer #本市新型农村合作医疗患者医疗总额
      add :bsxnhyj_num, :integer #本市新型农村合作医疗患者医技总额
      add :bsxnhypj_num, :integer #本市新型农村合作医疗患者药品总额
      add :bsxnhhl_num, :integer #本市新型农村合作医疗患者护理总额
      add :bsxnhgl_num, :integer #本市新型农村合作医疗患者管理总额
      add :bsxnh_avg, :float #本市新型农村合作医疗患者例均支付总额
      add :bsxnhzf_avg, :float #本市新型农村合作医疗患者例均自付总额
      add :bsxnhyl_avg, :float #本市新型农村合作医疗患者例均医疗总额
      add :bsxnhyj_avg, :float #本市新型农村合作医疗患者例均医技总额
      add :bsxnhypj_avg, :float #本市新型农村合作医疗患者例均药品总额
      add :bsxnhhl_avg, :float #本市新型农村合作医疗患者例均护理总额
      add :bsxnhgl_avg, :float #本市新型农村合作医疗患者例均管理总额
      add :bsxnh_rate, :float #本市新型农村合作医疗患者支付总额占比
      add :bsxnhzf_rate, :float #本市新型农村合作医疗患者自付总额占比
      add :bsxnhyl_rate, :float #本市新型农村合作医疗患者医疗总额占比
      add :bsxnhyj_rate, :float #本市新型农村合作医疗患者医技总额占比
      add :bsxnhypj_rate, :float #本市新型农村合作医疗患者药品总额占比
      add :bsxnhhl_rate, :float #本市新型农村合作医疗患者护理总额占比
      add :bsxnhgl_rate, :float #本市新型农村合作医疗患者管理总额占比
      add :wbxnh_num, :integer #外埠新型农村合作医疗患者支付总额
      add :wbxnhzf_num, :integer #外埠新型农村合作医疗患者自付总额
      add :wbxnhyl_num, :integer #外埠新型农村合作医疗患者医疗总额
      add :wbxnhyj_num, :integer #外埠新型农村合作医疗患者医技总额
      add :wbxnhypj_num, :integer #外埠新型农村合作医疗患者药品总额
      add :wbxnhhl_num, :integer #外埠新型农村合作医疗患者护理总额
      add :wbxnhgl_num, :integer #外埠新型农村合作医疗患者管理总额
      add :wbxnh_avg, :float #外埠新型农村合作医疗患者例均支付总额
      add :wbxnhzf_avg, :float #外埠新型农村合作医疗患者例均自付总额
      add :wbxnhyl_avg, :float #外埠新型农村合作医疗患者例均医疗总额
      add :wbxnhyj_avg, :float #外埠新型农村合作医疗患者例均医技总额
      add :wbxnhypj_avg, :float #外埠新型农村合作医疗患者例均药品总额
      add :wbxnhhl_avg, :float #外埠新型农村合作医疗患者例均护理总额
      add :wbxnhgl_avg, :float #外埠新型农村合作医疗患者例均管理总额
      add :wbxnh_rate, :float #外埠新型农村合作医疗患者支付总额占比
      add :wbxnhzf_rate, :float #外埠新型农村合作医疗患者自付总额占比
      add :wbxnhyl_rate, :float #外埠新型农村合作医疗患者医疗总额占比
      add :wbxnhyj_rate, :float #外埠新型农村合作医疗患者医技总额占比
      add :wbxnhypj_rate, :float #外埠新型农村合作医疗患者药品总额占比
      add :wbxnhhl_rate, :float #外埠新型农村合作医疗患者护理总额占比
      add :wbxnhgl_rate, :float #外埠新型农村合作医疗患者管理总额占比
      add :pkjz_num, :integer #贫困救助患者支付总额
      add :pkjzzf_num, :integer #贫困救助患者自付总额
      add :pkjzyl_num, :integer #贫困救助医疗总额
      add :pkjzyj_num, :integer #贫困救助医技总额
      add :pkjzypj_num, :integer #贫困救助药品总额
      add :pkjzhl_num, :integer #贫困救助护理总额
      add :pkjzgl_num, :integer #贫困救助管理总额
      add :pkjz_avg, :float #贫困救助患者例均支付总额
      add :pkjzzf_avg, :float #贫困救助患者例均自付总额
      add :pkjzyl_avg, :float #贫困救助例均医疗总额
      add :pkjzyj_avg, :float #贫困救助例均医技总额
      add :pkjzypj_avg, :float #贫困救助例均药品总额
      add :pkjzhl_avg, :float #贫困救助例均护理总额
      add :pkjzgl_avg, :float #贫困救助例均管理总额
      add :pkjz_rate, :float #贫困救助患者支付总额占比
      add :pkjzzf_rate, :float #贫困救助患者自付总额占比
      add :pkjzyl_rate, :float #贫困救助医疗总额占比
      add :pkjzyj_rate, :float #贫困救助医技总额占比
      add :pkjzypj_rate, :float #贫困救助药品总额占比
      add :pkjzhl_rate, :float #贫困救助护理总额占比
      add :pkjzgl_rate, :float #贫困救助管理总额占比
      add :sybx_num, :integer #商业医疗保险患者支付总额
      add :sybxzf_num, :integer #商业医疗保险患者自付总额
      add :sybxyl_num, :integer #商业医疗保险患者医疗总额
      add :sybxyj_num, :integer #商业医疗保险患者医技总额
      add :sybxypj_num, :integer #商业医疗保险患者药品总额
      add :sybxhl_num, :integer #商业医疗保险患者护理总额
      add :sybxgl_num, :integer #商业医疗保险患者管理总额
      add :sybx_avg, :float #商业医疗保险患者例均支付总额
      add :sybxzf_avg, :float #商业医疗保险患者例均自付总额
      add :sybxyl_avg, :float #商业医疗保险患者例均医疗总额
      add :sybxyj_avg, :float #商业医疗保险患者例均医技总额
      add :sybxypj_avg, :float #商业医疗保险患者例均药品总额
      add :sybxhl_avg, :float #商业医疗保险患者例均护理总额
      add :sybxgl_avg, :float #商业医疗保险患者例均管理总额
      add :sybx_rate, :float #商业医疗保险患者支付总额占比
      add :sybxzf_rate, :float #商业医疗保险患者自付总额占比
      add :sybxyl_rate, :float #商业医疗保险患者医疗总额占比
      add :sybxyj_rate, :float #商业医疗保险患者医技总额占比
      add :sybxypj_rate, :float #商业医疗保险患者药品总额占比
      add :sybxhl_rate, :float #商业医疗保险患者护理总额占比
      add :sybxgl_rate, :float #商业医疗保险患者管理总额占比
      add :qgf_num, :integer #全公费患者支付总额
      add :qgfzf_num, :integer #全公费患者自付总额
      add :qgfyl_num, :integer #全公费患者医疗总额
      add :qgfyj_num, :integer #全公费患者医技总额
      add :qgfypj_num, :integer #全公费患者药品总额
      add :qgfhl_num, :integer #全公费患者护理总额
      add :qgfgl_num, :integer #全公费患者管理总额
      add :qgf_avg, :float #全公费患者例均支付总额
      add :qgfzf_avg, :float #全公费患者例均自付总额
      add :qgfyl_avg, :float #全公费患者例均医疗总额
      add :qgfyj_avg, :float #全公费患者例均医技总额
      add :qgfypj_avg, :float #全公费患者例均药品总额
      add :qgfhl_avg, :float #全公费患者例均护理总额
      add :qgfgl_avg, :float #全公费患者例均管理总额
      add :qgf_rate, :float #全公费患者支付总额占比
      add :qgfzf_rate, :float #全公费患者自付总额占比
      add :qgfyl_rate, :float #全公费患者医疗总额占比
      add :qgfyj_rate, :float #全公费患者医技总额占比
      add :qgfypj_rate, :float #全公费患者药品总额占比
      add :qgfhl_rate, :float #全公费患者护理总额占比
      add :qgfgl_rate, :float #全公费患者管理总额占比
      add :qzf_num, :integer #全自费患者支付总额
      add :qzfyl_num, :integer #全自费患者医疗总额
      add :qzfyj_num, :integer #全自费患者医技总额
      add :qzfypj_num, :integer #全自费患者药品总额
      add :qzfhl_num, :integer #全自费患者护理总额
      add :qzfgl_num, :integer #全自费患者管理总额
      add :qzf_avg, :float #全自费患者例均支付总额
      add :qzfyl_avg, :float #全自费患者例均医疗总额
      add :qzfyj_avg, :float #全自费患者例均医技总额
      add :qzfypj_avg, :float #全自费患者例均药品总额
      add :qzfhl_avg, :float #全自费患者例均护理总额
      add :qzfgl_avg, :float #全自费患者例均管理总额
      add :qzf_rate, :float #全自费患者支付总额占比
      add :qzfyl_rate, :float #全自费患者医疗总额占比
      add :qzfyj_rate, :float #全自费患者医技总额占比
      add :qzfypj_rate, :float #全自费患者药品总额占比
      add :qzfhl_rate, :float #全自费患者护理总额占比
      add :qzfgl_rate, :float #全自费患者管理总额占比
      add :qtbx_num, :integer #其他社会保险患者支付总额
      add :qtbxzf_num, :integer #其他社会保险患者自付总额
      add :qtbxyl_num, :integer #其他社会保险医疗总额
      add :qtbxyj_num, :integer #其他社会保险医技总额
      add :qtbxypj_num, :integer #其他社会保险药品总额
      add :qtbxhl_num, :integer #其他社会保险护理总额
      add :qtbxgl_num, :integer #其他社会保险管理总额
      add :qtbx_avg, :float #其他社会保险患者例均支付总额
      add :qtbxzf_avg, :float #其他社会保险患者例均自付总额
      add :qtbxyl_avg, :float #其他社会保险例均医疗总额
      add :qtbxyj_avg, :float #其他社会保险例均医技总额
      add :qtbxypj_avg, :float #其他社会保险例均药品总额
      add :qtbxhl_avg, :float #其他社会保险例均护理总额
      add :qtbxgl_avg, :float #其他社会保险例均管理总额
      add :qtbx_rate, :float #其他社会保险患者支付总额占比
      add :qtbxzf_rate, :float #其他社会保险患者自付总额占比
      add :qtbxyl_rate, :float #其他社会保险医疗总额占比
      add :qtbxyj_rate, :float #其他社会保险医技总额占比
      add :qtbxypj_rate, :float #其他社会保险药品总额占比
      add :qtbxhl_rate, :float #其他社会保险护理总额占比
      add :qtbxgl_rate, :float #其他社会保险管理总额占比
      add :qthz_num, :integer #其他患者支付总额
      add :qthzzf_num, :integer #其他患者自付总额
      add :qthzyl_num, :integer #其他患者医疗总额
      add :qthzyj_num, :integer #其他患者医技总额
      add :qthzypj_num, :integer #其他患者药品总额
      add :qthzhl_num, :integer #其他患者护理总额
      add :qthzgl_num, :integer #其他患者管理总额
      add :qthz_avg, :float #其他患者例均支付总额
      add :qthzzf_avg, :float #其他患者例均自付总额
      add :qthzyl_avg, :float #其他患者例均医疗总额
      add :qthzyj_avg, :float #其他患者例均医技总额
      add :qthzypj_avg, :float #其他患者例均药品总额
      add :qthzhl_avg, :float #其他患者例均护理总额
      add :qthzgl_avg, :float #其他患者例均管理总额
      add :qthz_rate, :float #其他患者支付总额占比
      add :qthzzf_rate, :float #其他患者自付总额占比
      add :qthzyl_rate, :float #其他患者医疗总额占比
      add :qthzyj_rate, :float #其他患者医技总额占比
      add :qthzypj_rate, :float #其他患者药品总额占比
      add :qthzhl_rate, :float #其他患者护理总额占比
      add :qthzgl_rate, :float #其他患者管理总额占比
      add :ssywss_num, :integer #手术中意外损伤
      add :ssywqg_num, :integer #手术中意外切割
      add :ssywzc_num, :integer #手术中意外针刺
      add :ssywck_num, :integer #手术中意外穿孔
      add :ssywcx_num, :integer #手术中意外出血
      add :ssylyw_num, :integer #手术中体内遗留异物
      add :sswjsb_num, :integer #手术中无菌预防措施的失败
      add :ssczbd_num, :integer #手术中操作不当
      add :ssywss_rate, :float #手术中意外损伤占比
      add :ssywqg_rate, :float #手术中意外切割占比
      add :ssywzc_rate, :float #手术中意外针刺占比
      add :ssywck_rate, :float #手术中意外穿孔占比
      add :ssywcx_rate, :float #手术中意外出血占比
      add :ssylyw_rate, :float #手术中体内遗留异物占比
      add :sswjsb_rate, :float #手术中无菌预防措施的失败占比
      add :ssczbd_rate, :float #手术中操作不当
      add :zlywzl_num, :integer #治疗中意外损伤
      add :zlywqg_num, :integer #治疗中意外切割
      add :zlywzc_num, :integer #治疗中意外针刺
      add :zlywck_num, :integer #治疗中意外穿孔
      add :zlywcx_num, :integer #治疗中意外出血
      add :zlylyw_num, :integer #治疗中体内遗留异物
      add :zlwjsb_num, :integer #治疗中无菌预防措施的失败
      add :zlczbd_num, :integer #治疗中操作不当
      add :zlywzl_rate, :float #治疗中意外损伤占比
      add :zlywqg_rate, :float #治疗中意外切割占比
      add :zlywzc_rate, :float #治疗中意外针刺占比
      add :zlywck_rate, :float #治疗中意外穿孔占比
      add :zlywcx_rate, :float #治疗中意外出血占比
      add :zlylyw_rate, :float #治疗中体内遗留异物占比
      add :zlwjsb_rate, :float #治疗中无菌预防措施的失败占比
      add :zlczbd_rate, :float #治疗中操作不当
      add :szh_num, :integer #输注后感染
      add :czh_num, :integer #操作后伤口感染
      add :ssh_num, :integer #手术后切口感染
      add :stx_num, :integer #肾透析感染
      add :rgjt_num, :integer #人工假体植入感染
      add :ylqj_num, :integer #医疗器具感染
      add :szh_rate, :float #输注后感染占比
      add :czh_rate, :float #操作后伤口感染占比
      add :ssh_rate, :float #手术后切口感染占比
      add :stx_rate, :float #肾透析感染占比
      add :rgjt_rate, :float #人工假体植入感染占比
      add :ylqj_rate, :float #医疗器具感染占比
      add :ssls_num, :integer #手术例数
      add :mzzy_num, :integer #门诊住院病历数
      add :jzzy_num, :integer #急诊住院病历数
      add :ybzf_num, :integer #本市医保支付病历数
      add :xnh_num, :integer #本市新农合支付病历数
      add :qzfbl_num, :integer #全自费病历数
      add :qgfbl_num, :integer #全公费病历数
      add :ssls_rate, :float #手术例数占比
      add :mzzy_rate, :float #门诊住院病历数占比
      add :jzzy_rate, :float #急诊住院病历数占比
      add :ybzf_rate, :float #医保支付病历数占比
      add :xnh_rate, :float #本市新农合支付病历数占比
      add :qzfbl_rate, :float #全自费病历数占比
      add :qgfbl_rate, :float #全公费病历数占比
      add :hos_num, :integer #病例总数
      add :pc_num, :integer #排除病例数
      add :wrmdc_num, :integer #未入MDC病例数
      add :wrz_num, :integer #未入组病例数
      add :qy_num, :integer #QY病例数
      add :drg_rate, :float #入组率
      add :blood_num, :integer #输血总人数
      add :ablood_num, :integer #A型血型患者总人数
      add :bblood_num, :integer #B型血型患者总人数
      add :abblood_num, :integer #AB型血型患者总人数
      add :oblood_num, :integer #O型血型患者总人数
      add :wcblood_num, :integer #未查血型患者总人数
      add :blood_rate, :float #输血人数占比
      add :ablood_rate, :float #A型血型患者人数占比
      add :bblood_rate, :float #B型血型患者人数占比
      add :abblood_rate, :float #AB型血型患者人数占比
      add :oblood_rate, :float #O型血型患者人数占比
      add :wcblood_rate, :float #未查血型患者人数占比
      add :mz_num, :integer #麻醉总人数
      add :wmz_num, :integer #有手术无麻醉患者总人数
      add :qsmz_num, :integer #全身麻醉患者总人数
      add :xrmz_num, :integer #吸入麻醉（气管内插管、喉罩、面罩）患者总人数
      add :jmmz_num, :integer #静脉麻醉（全凭静脉麻醉）患者总人数
      add :jcmz_num, :integer #基础麻醉（直肠注入、肌肉注射）患者总人数
      add :qymz_num, :integer #区域麻醉患者总人数
      add :zgnmz_num, :integer #椎管内麻醉患者总人数
      add :mz_rate, :float #麻醉人数占比
      add :wmz_rate, :float #有手术无麻醉患者总人数占比
      add :qsmz_rate, :float #全身麻醉患者总人数占比
      add :xrmz_rate, :float #吸入麻醉（气管内插管、喉罩、面罩）患者总人数占比
      add :jmmz_rate, :float #静脉麻醉（全凭静脉麻醉）患者总人数占比
      add :jcmz_rate, :float #基础麻醉（直肠注入、肌肉注射）患者总人数占比
      add :qymz_rate, :float #区域麻醉患者总人数占比
      add :zgnmz_rate, :float #椎管内麻醉患者总人数占比
      add :ymwfh_num, :integer #蛛网膜下-硬膜外复合麻醉患者总人数
      add :fhmz_num, :integer #复合麻醉患者总人数
      add :btywfh_num, :integer #不同药物的复合：普鲁卡因静脉复合全麻，神经安定镇痛麻醉等患者总人数
      add :btfffh_num, :integer #不同方法的复合：静吸复合全麻，针药复合麻醉，全身-硬膜外复合麻醉，脊髓-硬膜外复合麻醉等患者总人数
      add :tsfffh_num, :integer #特殊方法的复合：全麻复合全身降温（低温麻醉）， 控制性降压等患者总人数
      add :jxfh_num, :integer #静吸复合麻醉患者总人数
      add :qtmz_num, :integer #其他麻醉患者总人数
      add :ymwfh_rate, :float #蛛网膜下-硬膜外复合麻醉患者总人数占比
      add :fhmz_rate, :float #复合麻醉患者总人数占比
      add :btywfh_rate, :float #不同药物的复合：普鲁卡因静脉复合全麻，神经安定镇痛麻醉等患者总人数占比
      add :btfffh_rate, :float #不同方法的复合：静吸复合全麻，针药复合麻醉，全身-硬膜外复合麻醉，脊髓-硬膜外复合麻醉等患者总人数占比
      add :tsfffh_rate, :float #特殊方法的复合：全麻复合全身降温（低温麻醉）， 控制性降压等患者总人数占比
      add :jxfh_rate, :float #静吸复合麻醉患者总人数占比
      add :qtmz_rate, :float #其他麻醉患者总人数占比
      add :zwmx_num, :integer #蛛网膜下腔阻滞患者总人数
      add :zwmx_rate, :float #蛛网膜下腔阻滞患者总人数占比
      add :ymw_num, :integer #硬膜外间隙阻滞（含骶管阻滞）患者总人数
      add :ymw_rate, :float #硬膜外间隙阻滞（含骶管阻滞）患者总人数占比
      # add :jc_num, :integer #颈丛阻滞患者总人数
      # add :jc_rate, :float #颈丛阻滞患者总人数占比
      add :sj_num, :integer #神经及神经丛阻滞患者总人数
      add :sj_rate, :float #神经及神经丛阻滞患者总人数占比
      add :bc_num, :integer #臂丛阻滞及上肢神经阻滞患者总人数
      add :yz_num, :integer #腰骶神经丛阻滞及下肢神经阻滞患者总人数
      add :qg_num, :integer #躯干神经阻滞：肋间神经阻滞患者总人数
      add :zp_num, :integer #椎旁神经阻滞患者总人数
      add :per_num, :integer #会阴神经阻滞患者总人数
      add :jg_num, :integer #交感神经阻滞：星状神经节阻滞患者总人数
      add :xy_num, :integer #胸腰交感神经阻滞患者总人数
      add :n_num, :integer #脑神经阻滞：三叉神经阻滞、舌咽神经阻滞患者总人数
      add :bc_rate, :float #臂丛阻滞及上肢神经阻滞患者总人数占比
      add :yz_rate, :float #腰骶神经丛阻滞及下肢神经阻滞患者总人数占比
      add :qg_rate, :float #躯干神经阻滞：肋间神经阻滞患者总人数占比
      add :zp_rate, :float #椎旁神经阻滞患者总人数占比
      add :per_rate, :float #会阴神经阻滞患者总人数占比
      add :jg_rate, :float #交感神经阻滞：星状神经节阻滞患者总人数占比
      add :xy_rate, :float #胸腰交感神经阻滞患者总人数占比
      add :n_rate, :float #脑神经阻滞：三叉神经阻滞、舌咽神经阻滞患者总人数占比
      add :baby_num, :integer #新生儿总数
      add :baby_rate, :float #新生儿总数占比
      add :boy_num, :integer #新生儿男孩数
      add :boy_rate, :float #新生儿男孩数占比
      add :girl_num, :integer #新生儿女孩数
      add :girl_rate, :float #新生儿女孩数占比
      add :def_num, :integer #新生儿缺陷总数
      add :def_rate, :float #新生儿缺陷总数占比
      add :ck_num, :integer #产科总例数
      add :ck_rate, :float #产科总例数占比
      add :pgc_num, :integer #剖宫产例数
      add :pgc_rate, :float #剖宫产例数占比
      add :sc_num, :integer #顺产例数
      add :sc_rate, :float #顺产例数占比
      add :dt_num, :integer #单胎总例数
      add :dt_rate, :float #单胎总例数占比
      add :sbt_num, :integer #双胞胎总例数
      add :sbt_rate, :float #双胞胎总例数占比
      add :dbt_num, :integer #多胞胎总例数
      add :dbt_rate, :float #多胞胎总例数占比
      add :st_num, :integer #死胎总例数
      add :st_rate, :float #死胎总例数占比
      add :xhqx_num, :integer #消化系统缺陷总例数
      add :sjqx_num, :integer #神经系统缺陷总例数
      add :hxqx_num, :integer #呼吸系统缺陷总例数
      add :xyqx_num, :integer #血液循环系统缺陷总例数
      add :ydqx_num, :integer #运动系统缺陷总例数
      add :nfmqx_num, :integer #内分泌系统缺陷总例数
      add :mnqx_num, :integer #泌尿系统缺陷总例数
      add :szqx_num, :integer #生殖系统缺陷总例数
      add :xhqx_rate, :float #消化系统缺陷总例数占比
      add :sjqx_rate, :float #神经系统缺陷总例数占比
      add :hxqx_rate, :float #呼吸系统缺陷总例数占比
      add :xyqx_rate, :float #血液循环系统缺陷总例数占比
      add :ydqx_rate, :float #运动系统缺陷总例数占比
      add :nfmqx_rate, :float #内分泌系统缺陷总例数占比
      add :mnqx_rate, :float #泌尿系统缺陷总例数占比
      add :szqx_rate, :float #生殖系统缺陷总例数占比
      timestamps()
    end

  end
end
