defmodule Stat.StatOrg do
  use Ecto.Schema
  import Ecto.Changeset
  alias Stat.StatOrg


  schema "stat_org" do
    field :time, :string #时间
    field :org, :string #机构名称
    field :true_org, :string
    field :num_sum, :integer #分析病历数
    field :death_num, :integer #死亡人数
    field :death_rate, :float # 死亡率
    field :death_rate_log, :float #死亡率对数
    field :icd10_num, :integer #icd10病历数
    field :day_avg, :float #平均住院日
    field :fee_avg, :float #平均费用
    field :death_age_avg, :float #平均死亡年龄
    field :weight, :float #权重
    field :int_time, :integer #时间排序
    field :weight_count, :float #总权重
    field :fee_index, :float #费用消耗指数
    field :day_index, :float #时间消耗指数
    field :cmi, :float #CMI
    field :org_type, :string
    field :time_type, :string

    # field :zdxg_num, :integer #诊断相关组数
    # field :wlzl_num, :integer #临床物理治疗病历数
    # field :jrzl_num, :integer #介入治疗病历数
    # field :tszl_num, :integer #特殊治疗病历数
    # field :kfzl_num, :integer #康复治疗病历数
    # field :zyzl_num, :integer #中医治疗病历数
    # field :ybzl_num, :integer #一般治疗病历数
    # field :jszl_num, :integer #精神治疗病历数
    # field :wlzl_rate, :float #临床物理治疗占比
    # field :jrzl_rate, :float #介入治疗占比
    # field :tszl_rate, :float #特殊治疗占比
    # field :kfzl_rate, :float #康复治疗占比
    # field :zyzl_rate, :float #中医治疗占比
    # field :ybzl_rate, :float #一般治疗占比
    # field :jszl_rate, :float #精神治疗占比
    # field :ccu_num, :integer #心脏监护室（CCU）总人数
    # field :ricu_num, :integer #呼吸监护室（RICU）总人数
    # field :sicu_num, :integer #外科监护室（SICU）总人数
    # field :nicu_num, :integer #新生儿监护室（NICU）总人数
    # field :picu_num, :integer #儿科监护室（PICU）总人数
    # field :other_num, :integer #其他监护室总人数
    # field :ccu_rate, :float #心脏监护室（CCU）总人数占比
    # field :ricu_rate, :float #呼吸监护室（RICU）总人数占比
    # field :sicu_rate, :float #外科监护室（SICU）总人数占比
    # field :nicu_rate, :float #新生儿监护室（NICU）总人数占比
    # field :picu_rate, :float #儿科监护室（PICU）总人数占比
    # field :other_rate, :float #其他监护室总人数占比
    # field :sjkfzc_num, :integer #实际开放总床日数
    # field :sjzyzc_num, :integer #实际占用总床日数
    # field :cyzzyzc_num, :integer #出院者占用总床日数
    # field :pjkfbc_num, :integer #平均开放病床数
    # field :bczz_num, :integer #病床周转次数
    # field :bcgzr_num, :integer #病床工作日
    # field :cyzpjzy_num, :integer #出院者平均住院日
    # field :bcsy_rate, :float #病床使用率
    # field :ylsy_num, :integer #医疗使用病历数
    # field :zl_num, :integer #诊疗病历数
    # field :zl_rate, :float #诊疗占比
    # field :jc_num, :integer #一般检查病历数
    # field :jc_rate, :float #一般检查占比
    # field :js_num, :integer #接生病历数
    # field :js_rate, :float #接生占比
    # field :yjsy_num, :integer #医技使用病历数
    # field :hsjc_num, :integer #核素检查病历数
    # field :hszl_num, :integer #核素治疗病历数
    # field :cszl_num, :integer #超声治疗病历数
    # field :fszl_num, :integer #放射治疗病历数
    # field :hy_num, :integer #化验病历数
    # field :bl_num, :integer #病理病历数
    # field :yjsy_rate, :float #医技使用病历数占比
    # field :hsjc_rate, :float #核素检查占比
    # field :hszl_rate, :float #核素治疗占比
    # field :cszl_rate, :float #超声治疗占比
    # field :fszl_rate, :float #放射治疗占比
    # field :hy_rate, :float #化验占比
    # field :bl_rate, :float #病理检验占比
    # field :hsjc_expense, :float #核素检查费
    # field :hszl_expense, :float #核素治疗费
    # field :cs_expense, :float #超声费
    # field :fs_expense, :float #放射费
    # field :hy_expense, :float #化验费
    # field :bl_expense, :float #病理费
    # field :avg_hsjc, :float #例均核素检查费
    # field :avg_hszl, :float #例均核素治疗费
    # field :avg_cs, :float #例均超声费
    # field :avg_fs, :float #例均放射费
    # field :avg_hy, :float #例均化验费
    # field :avg_bl, :float #例均病理费
    # # field :hsjc_rate, :float #核素检查费占比
    # # field :hszl_rate, :float #核素治疗费占比
    # field :csf_rate, :float #超声费占比
    # field :fsf_rate, :float #放射费占比
    # field :hyf_rate, :float #化验费占比
    # field :blf_rate, :float #病理费占比
    # field :jhfz_num, :integer #监护及辅助病历数
    # field :jhfz_rate, :float #监护及辅助占比
    # field :sx_num, :integer #输血病历数
    # field :sx_rate, :float #输血占比
    # field :sy_num, :integer #输氧使用病历数
    # field :sy_rate, :float #输氧人数占比
    # field :dfx_num, :integer #低风险组病历数
    # field :dfxsw_num, :integer #低风险组死亡人数
    # field :dfxsw_rate, :float #低风险组死亡率
    # field :dfx_age, :float #低风险平均死亡年龄
    # field :ysj_num, :integer #低风险组有尸检病历数
    # field :wsj_num, :integer #低风险组无尸检病历数
    # field :zdfx_num, :integer #中低风险组病历数
    # field :zdfxsw_num, :integer #中低风险组死亡人数
    # field :zdfxsw_rate, :float #中低风险组死亡率
    # field :zdfx_age, :float #中低风险平均死亡年龄
    # field :zdysj_num, :integer #中低风险组有尸检病历数
    # field :zdwsj_num, :integer #中低风险组无尸检病历数
    # field :zgfx_num, :integer #中高风险组病历数
    # field :zgfxsw_num, :integer #中高风险组死亡人数
    # field :zgfxsw_rate, :float #中高风险组死亡率
    # field :zgfx_age, :float #中高风险平均死亡年龄
    # field :zgysj_num, :integer #中高风险组有尸检病历数
    # field :zgwsj_num, :integer #中高风险组无尸检病历数
    # field :gfx_num, :integer #高风险组病历数
    # field :gfxsw_num, :integer #高风险组死亡人数
    # field :gfxsw_rate, :float #高风险组死亡率
    # field :gfx_age, :float #高风险组死亡年龄
    # field :gysj_num, :integer #高风险组有尸检病历数
    # field :gwsj_num, :integer #高风险组无尸检病历数
    # field :yl_expense, :float #医疗总费用
    # field :zl_expense, :float #诊察（诊疗）费
    # field :ybjc_expense, :float #一般检查费
    # field :js_expense, :float #接生费
    # field :mz_expense, :float #麻醉费
    # field :ss_expense, :float #手术费
    # field :avg_yl, :float #例均医疗费用
    # field :avg_zl, :float #例均诊察(诊疗)费
    # field :avg_ybjc, :float #例均一般检查费
    # field :avg_js, :float #例均接生费
    # field :avg_mz, :float #例均麻醉费
    # field :avg_ss, :float #例均手术费
    # field :yl_rate, :float #医疗费用占比
    # field :zlf_rate, :float #诊察（诊疗）费占比
    # field :ybjcf_rate, :float #一般检查费占比
    # field :jsf_rate, :float #接生费占比
    # field :mzf_rate, :float #麻醉费占比
    # field :ssf_rate, :float #手术费占比
    # field :jrzl_expense, :float #介入治疗费
    # field :tszl_expense, :float #特殊治疗费
    # field :kfzl_expense, :float #康复治疗费
    # field :zyzl_expense, :float #中医治疗费
    # field :ybzl_expense, :float #一般治疗费
    # field :jszl_expense, :float #精神治疗费
    # field :wlzl_expense, :float #临床物理治疗费
    # field :avg_jrzl, :float #例均介入治疗费
    # field :avg_tszl, :float #例均特殊治疗费
    # field :avg_kfzl, :float #例均康复治疗费
    # field :avg_zyzl, :float #例均中医治疗费
    # field :avg_ybzl, :float #例均一般治疗费
    # field :avg_jszl, :float #例均精神治疗费
    # field :avg_wlzl, :float #例均临床物理治疗费
    # field :jrzlf_rate, :float #介入治疗费占比
    # field :tszlf_rate, :float #特殊治疗费占比
    # field :kfzlf_rate, :float #康复治疗费占比
    # field :zyzlf_rate, :float #中医治疗费占比
    # field :ybzlf_rate, :float #一般治疗费占比
    # field :jszlf_rate, :float #精神治疗费占比
    # field :wlzlf_rate, :float #临床物理治疗费占比
    # field :glze_expense, :float #管理总额
    # field :jhfz_expense, :float #监护及辅助呼吸费
    # field :cw_expense, :float #床位费
    # field :gh_expense, :float #挂号费
    # field :sy_expense, :float #输氧费
    # field :other_expense, :float #其他费用
    # field :avg_glze, :float #例均管理总额
    # field :avg_jhfz, :float #例均监护及辅助呼吸费
    # field :avg_cw, :float #例均床位费
    # field :avg_gh, :float #例均挂号费
    # field :avg_sy, :float #例均输氧费
    # field :avg_other, :float #例均其他费用
    # field :glze_rate, :float #管理总额占比
    # field :jhfzf_rate, :float #监护及辅助呼吸费占比
    # field :cwf_rate, :float #床位费占比
    # field :ghf_rate, :float #挂号费占比
    # field :syf_rate, :float #输氧费占比
    # field :otherf_rate, :float #其他费用占比
    # field :zc_expense, :float #中成药费
    # field :zcy_expense, :float #中草药费
    # field :avg_zc, :float #例均中成药费
    # field :avg_zcy, :float #例均中草药费
    # field :zc_rate, :float #中成药费占比
    # field :zcy_rate, :float #中草药费占比
    # field :hlze_num, :integer #护理总额
    # field :hlzl_num, :integer #护理治疗费
    # field :hlf_num, :integer #护理费
    # field :hlzl_avg, :float #例均护理总额
    # field :hlf_avg, :float #例均护理治疗费
    # field :hlze_rate, :float #护理总额占比
    # field :hlzl_rate, :float #护理治疗费占比
    # field :hlf_rate, :float #护理费占比
    # field :sx_expense, :float #输血费
    # field :xy_expense, :float #西药费
    # field :kjy_expense, :float #抗菌药物费
    # field :bdb_expense, :float #白蛋白类制品费
    # field :qdb_expense, :float #球蛋白类制品费
    # field :nxyz_expense, :float #凝血因子类制品费
    # field :xbyz_expense, :float #细胞因子类制品费
    # field :avg_sxf, :float #例均输血费
    # field :avg_xyf, :float #例均西药费
    # field :avg_kjy, :float #例均抗菌药物费
    # field :avg_bdb, :float #例均白蛋白类制品费
    # field :avg_qdb, :float #例均球蛋白类制品费
    # field :avg_nxyz, :float #例均凝血因子类制品费
    # field :avg_xbyz, :float #例均细胞因子类制品费
    # field :sxf_rate, :float #输血费占比
    # field :xyf_rate, :float #西药费占比
    # field :kjy_rate, :float #抗菌药物费占比
    # field :bdb_rate, :float #白蛋白类制品费占比
    # field :qdb_rate, :float #球蛋白类制品费占比
    # field :nxyz_rate, :float #凝血因子类制品费占比
    # field :xbyz_rate, :float #细胞因子类制品费占比
    # field :ypzef, :float #药品总额
    # field :zlyc_expense, :float #治疗用一次性医用材料费
    # field :jryc_expense, :float #介入用一次性医用材料费
    # field :ssyc_expense, :float #手术用一次性医用材料费
    # field :jcyc_expense, :float #检查用一次性医用材料费
    # field :hc_expense, :float #耗材成本
    # field :avg_yp, :float #例均药品费用
    # field :avg_zlyc, :float #例均治疗用一次性医用材料费
    # field :avg_jryc, :float #例均介入用一次性医用材料费
    # field :avg_ssyc, :float #例均手术用一次性医用材料费
    # field :avg_jcyc, :float #例均检查用一次性医用材料费
    # field :avg_hc, :float #例均耗材成本
    # field :yp_rate, :float #药品总额占比
    # field :zlyc_rate, :float #治疗用一次性医用材料费占比
    # field :jryc_rate, :float #介入用一次性医用材料费占比
    # field :ssyc_rate, :float #手术用一次性医用材料费占比
    # field :jcyc_rate, :float #检查用一次性医用材料费占比
    # field :hc_rate, :float #耗材成本率
    # field :is_inhosp31, :integer #有出院31日再入院计划患者数
    # field :inhosp_rate, :float #再住院计划患者率
    # field :num_num1, :integer #出院当天再入院人数
    # field :num_rate1, :float #出院当天再入院率
    # field :num_num2, :integer #2-15再入院人数
    # field :num_rate2, :float #2-15再入院率
    # field :num_num3, :integer #16-31再入院人数
    # field :num_rate3, :float #16-31再入院人率
    # field :yzly_num, :integer #医嘱离院患者总人数
    # field :yzly_rate, :float #医嘱离院率
    # field :yzzy_num, :integer #医嘱转院患者总人数
    # field :yzzy_rate, :float #医嘱转院率
    # field :yzzsq_num, :integer #医嘱转社区卫生服务机构/乡镇卫生院患者总人数
    # field :yzzsq_rate, :float #医嘱转社区率
    # field :fyzly_num, :integer #非医嘱离院患者总人数
    # field :fyzly_rate, :float #非医嘱离院率
    # field :rycyfh_num, :integer #入院诊断与出院诊断符合人数
    # field :rycyfh_rate, :float #入院诊断与出院诊断符合率
    # field :zdblfh_num, :integer #诊断与病理诊断符合人数
    # field :zdblfh_rate, :float #诊断与病理诊断符合率
    # field :ryssfh_num, :integer #入院诊断与手术诊断符合人数
    # field :ryssfh_rate, :float #入院诊断与手术诊断符合率
    # field :hlfxsj_num, :integer #护理负性事件患者总数
    # field :syyw_num, :integer #输液意外损伤人数
    # field :syyl_num, :integer #输液遗留体内异物人数
    # field :syyf_num, :integer #输液无菌预防措施的失败人数
    # field :syry_num, :integer #输液时溶液稀释不当人数
    # field :sywr_num, :integer #输液器械的污染人数
    # field :sygl_num, :integer #输液液体过量人数
    # field :hlfxsj_rate, :float #护理负性事件患者总数占比
    # field :syyw_rate, :float #输液意外损伤人数占比
    # field :syyl_rate, :float #输液遗留体内异物人数占比
    # field :syyf_rate, :float #输液无菌预防措施的失败人数占比
    # field :syry_rate, :float #输液时溶液稀释不当人数占比
    # field :sywr_rate, :float #输液器械的污染人数占比
    # field :sygl_rate, :float #输液液体过量人数占比
    # field :sxfxsj_num, :integer #输血负性事件患者总数
    # field :sxyw_num, :integer #输血意外损伤人数
    # field :sxyl_num, :integer #输血遗留体内异物人数
    # field :sxyf_num, :integer #输血无菌预防措施的失败人数
    # field :sxwr_num, :integer #输血器械的污染人数
    # field :sxgl_num, :integer #输血液体过量人数
    # field :sxfxsj_rate, :float #输血负性事件患者总数占比
    # field :sxyw_rate, :float #输血意外损伤人数占比
    # field :sxyl_rate, :float #输血遗留体内异物人数占比
    # field :sxyf_rate, :float #输血无菌预防措施的失败人数占比
    # field :sxwr_rate, :float #输血器械的污染人数占比
    # field :sxgl_rate, :float #输血液体过量人数占比
    # field :ychz_num, :integer #压疮患者总数
    # field :odyc_num, :integer #Ⅰ度压疮患者数
    # field :wdyc_num, :integer #Ⅱ度压疮患者数
    # field :tdyc_num, :integer #Ⅲ度压疮患者数
    # field :fdyc_num, :integer #Ⅳ度压疮患者数
    # field :ychz_rate, :float #压疮患者总数占比
    # field :odyc_rate, :float #Ⅰ度压疮患者占比
    # field :wdyc_rate, :float #Ⅱ度压疮患者占比
    # field :tdyc_rate, :float #Ⅲ度压疮患者占比
    # field :fdyc_rate, :float #Ⅳ度压疮患者占比
    # field :ywdd_num, :integer #意外跌倒患者总数
    # field :ycdd_rate, :float #意外跌倒患者总数占比
    # field :zc_num, :integer #坠床患者总数
    # # field :zc_rate, :float #坠床患者总数占比
    # field :ywfxsj_num, :integer #药物负性事件患者总数
    # field :ywfxsj_rate, :float #药物负性事件患者总数占比
    # field :ywgl_num, :integer #药物过量人数
    # field :ywgl_rate, :float #药物过量占比
    # field :ywgc_num, :integer #药物给错总人数
    # field :ywgc_rate, :float #药物给错总人数占比
    # field :sqday_num, :integer #术前平均住院日
    # field :shday_num, :integer #术后平均住院日
    # field :fjh_num, :integer #非计划再次手术例数
    # field :fjh_rate, :float #非计划再次手术例数占比
    # field :zdss_num, :integer #重点手术例数
    # field :sw_num, :integer #死亡例数
    # field :sw_rate, :float #死亡例数占比
    # field :qklk_num, :integer #切口裂开患者总人数
    # field :qklk_rate, :float #切口裂开患者总人数占比
    # field :qkgr_num, :integer #切口感染患者总人数
    # field :qkgr_rate, :float #切口感染率总人数占比
    # field :shgr_num, :integer #术后感染例数
    # field :shgr_rate, :float #术后感染例数占比
    # field :shbf_num, :integer #术后并发症例数
    # field :shbf_rate, :float #术后并发症例数占比
    # field :yjqk_num, :integer #Ⅰ/甲切口愈合等级患者总人数
    # field :yjqk_rate, :float #Ⅰ/甲切口愈合等级患者总人数占比
    # field :ejqk_num, :integer #Ⅱ/甲切切口愈合等级患者总人数
    # field :ejqk_rate, :float #Ⅱ/甲切切口愈合等级患者总人数占比
    # field :sjqk_num, :integer #Ⅲ/甲切口愈合等级患者总人数
    # field :sjqk_rate, :float #Ⅲ/甲切口愈合等级患者总人数占比
    # field :yss_num, :integer #有手术，但体表无切口患者总人数
    # field :yss_rate, :float #有手术，但体表无切口患者人数占比
    # field :yjqtqk_num, :integer #Ⅰ/其他切口愈合等级患者总人数
    # field :yjqtqk_rate, :float #Ⅰ/其他切口愈合等级患者总人数占比
    # field :ejqtqk_num, :integer #Ⅱ/其他切口愈合等级患者总人数
    # field :ejqtqk_rate, :float #Ⅱ/其他切口愈合等级患者总人数占比
    # field :sjqtqk_num, :integer #Ⅲ/其他切口愈合等级患者总人数
    # field :sjqtqk_rate, :float #Ⅲ/其他切口愈合等级患者总人数占比
    # field :yjyqk_num, :integer #Ⅰ/乙切口愈合等级患者总人数
    # field :yjyqk_rate, :float #Ⅰ/乙切口愈合等级患者总人数占比
    # field :ejyqk_num, :integer #Ⅱ/乙切切口愈合等级患者总人数
    # field :ejyqk_rate, :float #Ⅱ/乙切切口愈合等级患者总人数占比
    # field :sjyqk_num, :integer #Ⅲ/乙切口愈合等级患者总人数
    # field :sjyqk_rate, :float #Ⅲ/乙切口愈合等级患者总人数占比
    # field :yjbqk_num, :integer #Ⅰ/丙切口愈合等级患者总人数
    # field :yjbqk_rate, :float #Ⅰ/丙切口愈合等级患者总人数占比
    # field :ejbqk_num, :integer #Ⅱ/丙切口愈合等级患者总人数
    # field :ejbqk_rate, :float #Ⅱ/丙切口愈合等级患者总人数占比
    # field :sjbqk_num, :integer #Ⅲ/丙切口愈合等级患者总人数
    # field :sjbqk_rate, :float #Ⅲ/丙切口愈合等级患者总人数占比
    # field :ojss_num, :integer #一级手术患者总人数
    # field :ojss_rate, :float #一级手术患者总人数占比
    # field :wjss_num, :integer #二级手术患者总人数
    # field :wjss_rate, :float #二级手术患者总人数占比
    # field :tjss_num, :integer #三级手术患者总人数
    # field :tjss_rate, :float #三级手术患者总人数占比
    # field :fjss_num, :integer #四级手术患者总人数
    # field :fjss_rate, :float #四级手术患者总人数占比
    # field :bazlj_num, :integer #病案质量为甲级病案总数
    # field :bazlj_rate, :float #病案质量为甲级病案总数占比
    # field :bazly_num, :integer #病案质量为乙级病案总数
    # field :bazly_rate, :float #病案质量为乙级病案总数占比
    # field :bazlb_num, :integer #病案质量为丙级病案总数
    # field :bazlb_rate, :float #病案质量为丙级病案总数占比
    # field :tl_num, :integer #肿瘤患者T0期总人数
    # field :to_num, :integer #肿瘤患者T1期总人数
    # field :tw_num, :integer #肿瘤患者T2期总人数
    # field :tt_num, :integer #肿瘤患者T3期总人数
    # field :tf_num, :integer #肿瘤患者T4期总人数
    # field :wfpgyf_num, :integer #肿瘤患者无法评估原发肿瘤大小总人数
    # field :tl_rate, :float #肿瘤患者T0期总人数占比
    # field :to_rate, :float #肿瘤患者T1期总人数占比
    # field :tw_rate, :float #肿瘤患者T2期总人数占比
    # field :tt_rate, :float #肿瘤患者T3期总人数占比
    # field :tf_rate, :float #肿瘤患者T4期总人数占比
    # field :wfpgyf_rate, :float #肿瘤患者无法评估原发肿瘤大小总人数占比
    # field :nl_num, :integer #肿瘤患者N0期总人数
    # field :no_num, :integer #肿瘤患者N1期总人数
    # field :nw_num, :integer #肿瘤患者N2期总人数
    # field :nt_num, :integer #肿瘤患者N3期总人数
    # field :nf_num, :integer #肿瘤患者N4期总人数
    # field :wfpglb_num, :integer #肿瘤患者无法评估区域淋巴结有无转移总人数
    # field :nl_rate, :float #肿瘤患者N0期总人数占比
    # field :no_rate, :float #肿瘤患者N1期总人数占比
    # field :nw_rate, :float #肿瘤患者N2期总人数占比
    # field :nt_rate, :float #肿瘤患者N3期总人数占比
    # field :nf_rate, :float #肿瘤患者N4期总人数占比
    # field :wfpglb_rate, :float #肿瘤患者无法评估区域淋巴结有无转移总人数占比
    # field :ml_num, :integer #肿瘤患者M0期总人数
    # field :ml_rate, :float #肿瘤患者M0期总人数占比
    # field :mo_num, :integer #肿瘤患者M1期总人数
    # field :mo_rate, :float #肿瘤患者M1期总人数占比
    # field :wfpgyc_num, :integer #肿瘤患者无法评估远处是否转移总人数
    # field :wfpgyc_rate, :float #肿瘤患者无法评估远处是否转移总人数占比
    # field :man_num, :integer #男性患者
    # field :man_rate, :float #男性患者占比
    # field :woman_num, :integer #女性患者
    # field :woman_rate, :float #女性患者占比
    # field :bd_num, :integer #本地患者数
    # field :bd_rate, :float #本地患者数占比
    # field :wd_num, :integer #外地患者数
    # field :wd_rate, :float #外地患者数占比
    # field :xhxt_num, :integer #消化系统总人数
    # field :sjxt_num, :integer #神经系统总人数
    # field :hxxt_num, :integer #呼吸系统总人数
    # field :xyxh_num, :integer #血液循环系统总人数
    # field :ydxt_num, :integer #运动系统总人数
    # field :nfm_num, :integer #内分泌系统总人数
    # field :mnxt_num, :integer #泌尿系统总人数
    # field :szxt_num, :integer #生殖系统总人数
    # field :xhxt_rate, :float #消化系统总人数占比
    # field :sjxt_rate, :float #神经系统总人数占比
    # field :hxxt_rate, :float #呼吸系统总人数占比
    # field :xyxh_rate, :float #血液循环系统总人数占比
    # field :ydxt_rate, :float #运动系统总人数占比
    # field :nfm_rate, :float #内分泌系统总人数占比
    # field :mnxt_rate, :float #泌尿系统总人数占比
    # field :szxt_rate, :float #生殖系统总人数占比
    # field :zlfq_num, :integer #肿瘤分期不详患者总人数
    # field :gfh_num, :integer #高分化程度患者总人数
    # field :zfh_num, :integer #中分化程度患者总人数
    # field :dfh_num, :integer #低分化程度患者总人数
    # field :wfh_num, :integer #未分化程度患者总人数
    # field :wqd_num, :integer #未确定程度患者总人数
    # field :zlfq_rate, :float #肿瘤分期不详患者总人数占比
    # field :gfh_rate, :float #高分化程度患者总人数占比
    # field :zfh_rate, :float #中分化程度患者总人数占比
    # field :dfh_rate, :float #低分化程度患者总人数占比
    # field :wfh_rate, :float #未分化程度患者总人数占比
    # field :wqd_rate, :float #未确定程度患者总人数占比
    # field :txb_num, :integer #T细胞程度患者总人数
    # field :txb_rate, :float #T细胞程度患者总人数占比
    # field :bxb_num, :integer #B细胞程度患者总人数
    # field :bxb_rate, :float #B细胞程度患者总人数占比
    # field :ftfbxb_num, :integer #非T-非B程度患者总人数
    # field :ftfbxb_rate, :float #非T-非B程度患者总人数占比
    # field :nk_num, :integer #NK（自然杀伤）细胞程度患者总人数
    # field :nk_rate, :float #NK（自然杀伤）细胞程度患者总人数占比
    # field :lczg_num, :integer #临床诊断作为最高诊断依据患者总人数
    # field :xxct_num, :integer #X线、CT、超声波、内窥镜等诊断作为最高诊断依据患者总人数
    # field :sszd_num, :integer #手术诊断作为最高诊断依据患者总人数
    # field :shmy_num, :integer #生化、免疫诊断作为最高诊断依据患者总人数
    # field :xbx_num, :integer #细胞学、血片诊断作为最高诊断依据患者总人数
    # field :bljf_num, :integer #病理（继发）诊断作为最高诊断依据患者总人数
    # field :blyf_num, :integer #病理（原发）诊断作为最高诊断依据患者总人数
    # field :sjybl_num, :integer #尸检（有病理）诊断作为最高诊断依据患者总人数
    # field :zgzdyj_num, :integer #最高诊断依据不详患者总人数
    # field :lczg_rate, :float #临床诊断作为最高诊断依据患者总人数占比
    # field :xxct_rate, :float #X线、CT、超声波、内窥镜等诊断作为最高诊断依据患者总人数占比
    # field :sszd_rate, :float #手术诊断作为最高诊断依据患者总人数占比
    # field :shmy_rate, :float #生化、免疫诊断作为最高诊断依据患者总人数占比
    # field :xbx_rate, :float #细胞学、血片诊断作为最高诊断依据患者总人数占比
    # field :bljf_rate, :float #病理（继发）诊断作为最高诊断依据患者总人数占比
    # field :blyf_rate, :float #病理（原发）诊断作为最高诊断依据患者总人数占比
    # field :sjybl_rate, :float #尸检（有病理）诊断作为最高诊断依据患者总人数占比
    # field :zgzdyj_rate, :float #最高诊断依据不详患者总人数占比
    # field :rhya_num, :integer #RH阴性_A型血型患者总人数
    # field :rhya_rate, :float #RH阴性_A型血型患者总人数占比
    # field :rhyb_num, :integer #RH阴性_B型血型患者总人数
    # field :rhyb_rate, :float #RH阴性_B型血型患者总人数占比
    # field :rhyo_num, :integer #RH阴性_O型血型患者总人数
    # field :rhyo_rate, :float #RH阴性_O型血型患者总人数占比
    # field :rhyab_num, :integer #RH阴性_AB型血型患者总人数
    # field :rhyab_rate, :float #RH阴性_AB型血型患者总人数占比
    # field :rhbxa_num, :integer #RH不详_A型血型患者总人数
    # field :rhbxa_rate, :float #RH不详_A型血型患者总人数占比
    # field :rhbxb_num, :integer #RH不详_B型血型患者总人数
    # field :rhbxb_rate, :float #RH不详_B型血型患者总人数占比
    # field :rhbxo_num, :integer #RH不详_O型血型患者总人数
    # field :rhbxo_rate, :float #RH不详_O型血型患者总人数占比
    # field :rhbxab_num, :integer #RH不详_AB型血型患者总人数
    # field :rhbxab_rate, :float #RH不详_AB型血型患者总人数占比
    # field :rhyxa_num, :integer #RH阳性_A型血型患者总人数
    # field :rhyxa_rate, :float #RH阳性_A型血型患者总人数占比
    # field :rhyxb_num, :integer #RH阳性_B型血型患者总人数
    # field :rhyxb_rate, :float #RH阳性_B型血型患者总人数占比
    # field :rhyxo_num, :integer #RH阳性_O型血型患者总人数
    # field :rhyxo_rate, :float #RH阳性_O型血型患者总人数占比
    # field :rhyxab_num, :integer #RH阳性_AB型血型患者总人数
    # field :rhyxab_rate, :float #RH阳性_AB型血型患者总人数占比
    # field :rhyxa_cc, :integer #Rh阳性_A型血型使用总单位数
    # field :rhyxb_cc, :integer #Rh阳性_B型血型使用总单位数
    # field :rhyxab_cc, :integer #Rh阳性_AB型血型使用总单位数
    # field :rhyxo_cc, :integer #Rh阳性_O型血型使用总单位数
    # field :rhyxacc_rate, :float #Rh阳性_A型血型使用总单位数占比
    # field :rhyxbcc_rate, :float #Rh阳性_B型血型使用总单位数占比
    # field :rhyxabcc_rate, :float #Rh阳性_AB型血型使用总单位数占比
    # field :rhyx0cc_rate, :float #Rh阳性_O型血型使用总单位数占比
    # field :rhyacc_rate, :float #Rh阴性_A型血型使用总单位数占比
    # field :rhybcc_rate, :float #Rh阴性_B型血型使用总单位数占比
    # field :rhyabcc_rate, :float #Rh阴性_AB型血型使用总单位数占比
    # field :rhy0cc_rate, :float #Rh阴性_O型血型使用总单位数占比
    # field :rhya_cc, :integer #Rh阴性_A型血型使用总单位数
    # field :rhyb_cc, :integer #Rh阴性_B型血型使用总单位数
    # field :rhyab_cc, :integer #Rh阴性_AB型血型使用总单位数
    # field :rhyo_cc, :integer #Rh阴性_O型血型使用总单位数
    # field :cfx_num, :integer #成分血总单位数
    # field :hxb_num, :integer #红细胞使用总单位数
    # field :xsb_num, :integer #血小板使用总单位数
    # field :xj_num, :integer #血浆使用总单位数
    # field :qx_num, :integer #全血使用总单位数
    # field :qtx_num, :integer #其它血制品使用总单位数
    # field :cfx_avg, :float #例均成分血使用总单位数
    # field :hxb_avg, :float #例均红细胞使用总单位数
    # field :xsb_avg, :float #例均血小板使用总单位数
    # field :xj_avg, :float #例均血浆使用总单位数
    # field :qx_avg, :float #例均全血使用总单位数
    # field :qtx_avg, :float #例均其它血制品使用总单位数
    # field :cfx_rate, :float #成分血总单位数占比
    # field :hxb_rate, :float #红细胞使用总单位数占比
    # field :xsb_rate, :float #血小板使用总单位数占比
    # field :xj_rate, :float #血浆使用总单位数占比
    # field :qx_rate, :float #全血使用总单位数占比
    # field :qtx_rate, :float #其它血制品使用总单位数占比
    # field :bszg_num, :integer #本市城镇职工基本医疗保险患者支付总额
    # field :bszgzf_num, :integer #本市城镇职工基本医疗保险患者自付总额
    # field :bszgyl_num, :integer #本市城镇职工基本医疗保险患者医疗总额
    # field :bszgyj_num, :integer #本市城镇职工基本医疗保险患者医技总额
    # field :bszgypj_num, :integer #本市城镇职工基本医疗保险患者药品总额
    # field :bszghl_num, :integer #本市城镇职工基本医疗保险患者护理总额
    # field :bszggl_num, :integer #本市城镇职工基本医疗保险患者管理总额
    # field :bszg_avg, :float #本市城镇职工基本医疗保险患者例均支付总额
    # field :bszgzf_avg, :float #本市城镇职工基本医疗保险患者例均自付总额
    # field :bszgyl_avg, :float #本市城镇职工基本医疗保险患者例均医疗总额
    # field :bszgyj_avg, :float #本市城镇职工基本医疗保险患者例均医技总额
    # field :bszgypj_avg, :float #本市城镇职工基本医疗保险患者例均药品总额
    # field :bszghl_avg, :float #本市城镇职工基本医疗保险患者例均护理总额
    # field :bszggl_avg, :float #本市城镇职工基本医疗保险患者例均管理总额
    # field :bszg_rate, :float #本市城镇职工基本医疗保险患者支付总额占比
    # field :bszgzf_rate, :float #本市城镇职工基本医疗保险患者自付总额占比
    # field :bszgyl_rate, :float #本市城镇职工基本医疗保险患者医疗总额占比
    # field :bszgyj_rate, :float #本市城镇职工基本医疗保险患者医技总额占比
    # field :bszgypj_rate, :float #本市城镇职工基本医疗保险患者药品总额占比
    # field :bszghl_rate, :float #本市城镇职工基本医疗保险患者护理总额占比
    # field :bszggl_rate, :float #本市城镇职工基本医疗保险患者管理总额占比
    # field :wbzg_num, :integer #外埠城镇职工基本医疗保险患者支付总额
    # field :wbzgzf_num, :integer #外埠城镇职工基本医疗保险患者自付总额
    # field :wbzgyl_num, :integer #外埠城镇职工基本医疗保险患者医疗总额
    # field :wbzgyj_num, :integer #外埠城镇职工基本医疗保险患者医技总额
    # field :wbzgypj_num, :integer #外埠城镇职工基本医疗保险患者药品总额
    # field :wbzghl_num, :integer #外埠城镇职工基本医疗保险患者护理总额
    # field :wbzggl_num, :integer #外埠城镇职工基本医疗保险患者管理总额
    # field :wbzg_avg, :float #外埠城镇职工基本医疗保险患者例均支付总额
    # field :wbzgzf_avg, :float #外埠城镇职工基本医疗保险患者例均自付总额
    # field :wbzgyl_avg, :float #外埠城镇职工基本医疗保险患者例均医疗总额
    # field :wbzgyj_avg, :float #外埠城镇职工基本医疗保险患者例均医技总额
    # field :wbzgypj_avg, :float #外埠城镇职工基本医疗保险患者例均药品总额
    # field :wbzghl_avg, :float #外埠城镇职工基本医疗保险患者例均护理总额
    # field :wbzggl_avg, :float #外埠城镇职工基本医疗保险患者例均管理总额
    # field :wbzg_rate, :float #外埠城镇职工基本医疗保险患者支付总额占比
    # field :wbzgzf_rate, :float #外埠城镇职工基本医疗保险患者自付总额占比
    # field :wbzgyl_rate, :float #外埠城镇职工基本医疗保险患者医疗总额占比
    # field :wbzgyj_rate, :float #外埠城镇职工基本医疗保险患者医技总额占比
    # field :wbzgypj_rate, :float #外埠城镇职工基本医疗保险患者药品总额占比
    # field :wbzghl_rate, :float #外埠城镇职工基本医疗保险患者护理总额占比
    # field :wbzggl_rate, :float #外埠城镇职工基本医疗保险患者管理总额占比
    # field :bsjm_num, :integer #本市城镇居民基本医疗保险患者支付总额
    # field :bsjmzf_num, :integer #本市城镇居民基本医疗保险患者自付总额
    # field :bsjmyl_num, :integer #本市城镇居民基本医疗保险患者医疗总额
    # field :bsjmyj_num, :integer #本市城镇居民基本医疗保险患者医技总额
    # field :bsjmypj_num, :integer #本市城镇居民基本医疗保险患者药品总额
    # field :bsjmhl_num, :integer #本市城镇居民基本医疗保险患者护理总额
    # field :bsjmgl_num, :integer #本市城镇居民基本医疗保险患者管理总额
    # field :bsjm_avg, :float #本市城镇居民基本医疗保险患者例均支付总额
    # field :bsjmzf_avg, :float #本市城镇居民基本医疗保险患者例均自付总额
    # field :bsjmyl_avg, :float #本市城镇居民基本医疗保险患者例均医疗总额
    # field :bsjmyj_avg, :float #本市城镇居民基本医疗保险患者例均医技总额
    # field :bsjmypj_avg, :float #本市城镇居民基本医疗保险患者例均药品总额
    # field :bsjmhl_avg, :float #本市城镇居民基本医疗保险患者例均护理总额
    # field :bsjmgl_avg, :float #本市城镇居民基本医疗保险患者例均管理总额
    # field :bsjm_rate, :float #本市城镇居民基本医疗保险患者支付总额占比
    # field :bsjmzf_rate, :float #本市城镇居民基本医疗保险患者自付总额占比
    # field :bsjmyl_rate, :float #本市城镇居民基本医疗保险患者医疗总额占比
    # field :bsjmyj_rate, :float #本市城镇居民基本医疗保险患者医技总额占比
    # field :bsjmypj_rate, :float #本市城镇居民基本医疗保险患者药品总额占比
    # field :bsjmhl_rate, :float #本市城镇居民基本医疗保险患者护理总额占比
    # field :bsjmgl_rate, :float #本市城镇居民基本医疗保险患者管理总额占比
    # field :wbjm_num, :integer #外埠城镇居民基本医疗保险患者支付总额
    # field :wbjmzf_num, :integer #外埠城镇居民基本医疗保险患者自付总额
    # field :wbjmyl_num, :integer #外埠城镇居民基本医疗保险患者医疗总额
    # field :wbjmyj_num, :integer #外埠城镇居民基本医疗保险患者医技总额
    # field :wbjmypj_num, :integer #外埠城镇居民基本医疗保险患者药品总额
    # field :wbjmhl_num, :integer #外埠城镇居民基本医疗保险患者护理总额
    # field :wbjmgl_num, :integer #外埠城镇居民基本医疗保险患者管理总额
    # field :wbjm_avg, :float #外埠城镇居民基本医疗保险患者例均支付总额
    # field :wbjmzf_avg, :float #外埠城镇居民基本医疗保险患者例均自付总额
    # field :wbjmyl_avg, :float #外埠城镇居民基本医疗保险患者例均医疗总额
    # field :wbjmyj_avg, :float #外埠城镇居民基本医疗保险患者例均医技总额
    # field :wbjmypj_avg, :float #外埠城镇居民基本医疗保险患者例均药品总额
    # field :wbjmhl_avg, :float #外埠城镇居民基本医疗保险患者例均护理总额
    # field :wbjmgl_avg, :float #外埠城镇居民基本医疗保险患者例均管理总额
    # field :wbjm_rate, :float #外埠城镇居民基本医疗保险患者支付总额占比
    # field :wbjmzf_rate, :float #外埠城镇居民基本医疗保险患者自付总额占比
    # field :wbjmyl_rate, :float #外埠城镇居民基本医疗保险患者医疗总额占比
    # field :wbjmyj_rate, :float #外埠城镇居民基本医疗保险患者医技总额占比
    # field :wbjmypj_rate, :float #外埠城镇居民基本医疗保险患者药品总额占比
    # field :wbjmhl_rate, :float #外埠城镇居民基本医疗保险患者护理总额占比
    # field :wbjmgl_rate, :float #外埠城镇居民基本医疗保险患者管理总额占比
    # field :bsxnh_num, :integer #本市新型农村合作医疗患者支付总额
    # field :bsxnhzf_num, :integer #本市新型农村合作医疗患者自付总额
    # field :bsxnhyl_num, :integer #本市新型农村合作医疗患者医疗总额
    # field :bsxnhyj_num, :integer #本市新型农村合作医疗患者医技总额
    # field :bsxnhypj_num, :integer #本市新型农村合作医疗患者药品总额
    # field :bsxnhhl_num, :integer #本市新型农村合作医疗患者护理总额
    # field :bsxnhgl_num, :integer #本市新型农村合作医疗患者管理总额
    # field :bsxnh_avg, :float #本市新型农村合作医疗患者例均支付总额
    # field :bsxnhzf_avg, :float #本市新型农村合作医疗患者例均自付总额
    # field :bsxnhyl_avg, :float #本市新型农村合作医疗患者例均医疗总额
    # field :bsxnhyj_avg, :float #本市新型农村合作医疗患者例均医技总额
    # field :bsxnhypj_avg, :float #本市新型农村合作医疗患者例均药品总额
    # field :bsxnhhl_avg, :float #本市新型农村合作医疗患者例均护理总额
    # field :bsxnhgl_avg, :float #本市新型农村合作医疗患者例均管理总额
    # field :bsxnh_rate, :float #本市新型农村合作医疗患者支付总额占比
    # field :bsxnhzf_rate, :float #本市新型农村合作医疗患者自付总额占比
    # field :bsxnhyl_rate, :float #本市新型农村合作医疗患者医疗总额占比
    # field :bsxnhyj_rate, :float #本市新型农村合作医疗患者医技总额占比
    # field :bsxnhypj_rate, :float #本市新型农村合作医疗患者药品总额占比
    # field :bsxnhhl_rate, :float #本市新型农村合作医疗患者护理总额占比
    # field :bsxnhgl_rate, :float #本市新型农村合作医疗患者管理总额占比
    # field :wbxnh_num, :integer #外埠新型农村合作医疗患者支付总额
    # field :wbxnhzf_num, :integer #外埠新型农村合作医疗患者自付总额
    # field :wbxnhyl_num, :integer #外埠新型农村合作医疗患者医疗总额
    # field :wbxnhyj_num, :integer #外埠新型农村合作医疗患者医技总额
    # field :wbxnhypj_num, :integer #外埠新型农村合作医疗患者药品总额
    # field :wbxnhhl_num, :integer #外埠新型农村合作医疗患者护理总额
    # field :wbxnhgl_num, :integer #外埠新型农村合作医疗患者管理总额
    # field :wbxnh_avg, :float #外埠新型农村合作医疗患者例均支付总额
    # field :wbxnhzf_avg, :float #外埠新型农村合作医疗患者例均自付总额
    # field :wbxnhyl_avg, :float #外埠新型农村合作医疗患者例均医疗总额
    # field :wbxnhyj_avg, :float #外埠新型农村合作医疗患者例均医技总额
    # field :wbxnhypj_avg, :float #外埠新型农村合作医疗患者例均药品总额
    # field :wbxnhhl_avg, :float #外埠新型农村合作医疗患者例均护理总额
    # field :wbxnhgl_avg, :float #外埠新型农村合作医疗患者例均管理总额
    # field :wbxnh_rate, :float #外埠新型农村合作医疗患者支付总额占比
    # field :wbxnhzf_rate, :float #外埠新型农村合作医疗患者自付总额占比
    # field :wbxnhyl_rate, :float #外埠新型农村合作医疗患者医疗总额占比
    # field :wbxnhyj_rate, :float #外埠新型农村合作医疗患者医技总额占比
    # field :wbxnhypj_rate, :float #外埠新型农村合作医疗患者药品总额占比
    # field :wbxnhhl_rate, :float #外埠新型农村合作医疗患者护理总额占比
    # field :wbxnhgl_rate, :float #外埠新型农村合作医疗患者管理总额占比
    # field :pkjz_num, :integer #贫困救助患者支付总额
    # field :pkjzzf_num, :integer #贫困救助患者自付总额
    # field :pkjzyl_num, :integer #贫困救助医疗总额
    # field :pkjzyj_num, :integer #贫困救助医技总额
    # field :pkjzypj_num, :integer #贫困救助药品总额
    # field :pkjzhl_num, :integer #贫困救助护理总额
    # field :pkjzgl_num, :integer #贫困救助管理总额
    # field :pkjz_avg, :float #贫困救助患者例均支付总额
    # field :pkjzzf_avg, :float #贫困救助患者例均自付总额
    # field :pkjzyl_avg, :float #贫困救助例均医疗总额
    # field :pkjzyj_avg, :float #贫困救助例均医技总额
    # field :pkjzypj_avg, :float #贫困救助例均药品总额
    # field :pkjzhl_avg, :float #贫困救助例均护理总额
    # field :pkjzgl_avg, :float #贫困救助例均管理总额
    # field :pkjz_rate, :float #贫困救助患者支付总额占比
    # field :pkjzzf_rate, :float #贫困救助患者自付总额占比
    # field :pkjzyl_rate, :float #贫困救助医疗总额占比
    # field :pkjzyj_rate, :float #贫困救助医技总额占比
    # field :pkjzypj_rate, :float #贫困救助药品总额占比
    # field :pkjzhl_rate, :float #贫困救助护理总额占比
    # field :pkjzgl_rate, :float #贫困救助管理总额占比
    # field :sybx_num, :integer #商业医疗保险患者支付总额
    # field :sybxzf_num, :integer #商业医疗保险患者自付总额
    # field :sybxyl_num, :integer #商业医疗保险患者医疗总额
    # field :sybxyj_num, :integer #商业医疗保险患者医技总额
    # field :sybxypj_num, :integer #商业医疗保险患者药品总额
    # field :sybxhl_num, :integer #商业医疗保险患者护理总额
    # field :sybxgl_num, :integer #商业医疗保险患者管理总额
    # field :sybx_avg, :float #商业医疗保险患者例均支付总额
    # field :sybxzf_avg, :float #商业医疗保险患者例均自付总额
    # field :sybxyl_avg, :float #商业医疗保险患者例均医疗总额
    # field :sybxyj_avg, :float #商业医疗保险患者例均医技总额
    # field :sybxypj_avg, :float #商业医疗保险患者例均药品总额
    # field :sybxhl_avg, :float #商业医疗保险患者例均护理总额
    # field :sybxgl_avg, :float #商业医疗保险患者例均管理总额
    # field :sybx_rate, :float #商业医疗保险患者支付总额占比
    # field :sybxzf_rate, :float #商业医疗保险患者自付总额占比
    # field :sybxyl_rate, :float #商业医疗保险患者医疗总额占比
    # field :sybxyj_rate, :float #商业医疗保险患者医技总额占比
    # field :sybxypj_rate, :float #商业医疗保险患者药品总额占比
    # field :sybxhl_rate, :float #商业医疗保险患者护理总额占比
    # field :sybxgl_rate, :float #商业医疗保险患者管理总额占比
    # field :qgf_num, :integer #全公费患者支付总额
    # field :qgfzf_num, :integer #全公费患者自付总额
    # field :qgfyl_num, :integer #全公费患者医疗总额
    # field :qgfyj_num, :integer #全公费患者医技总额
    # field :qgfypj_num, :integer #全公费患者药品总额
    # field :qgfhl_num, :integer #全公费患者护理总额
    # field :qgfgl_num, :integer #全公费患者管理总额
    # field :qgf_avg, :float #全公费患者例均支付总额
    # field :qgfzf_avg, :float #全公费患者例均自付总额
    # field :qgfyl_avg, :float #全公费患者例均医疗总额
    # field :qgfyj_avg, :float #全公费患者例均医技总额
    # field :qgfypj_avg, :float #全公费患者例均药品总额
    # field :qgfhl_avg, :float #全公费患者例均护理总额
    # field :qgfgl_avg, :float #全公费患者例均管理总额
    # field :qgf_rate, :float #全公费患者支付总额占比
    # field :qgfzf_rate, :float #全公费患者自付总额占比
    # field :qgfyl_rate, :float #全公费患者医疗总额占比
    # field :qgfyj_rate, :float #全公费患者医技总额占比
    # field :qgfypj_rate, :float #全公费患者药品总额占比
    # field :qgfhl_rate, :float #全公费患者护理总额占比
    # field :qgfgl_rate, :float #全公费患者管理总额占比
    # field :qzf_num, :integer #全自费患者支付总额
    # field :qzfyl_num, :integer #全自费患者医疗总额
    # field :qzfyj_num, :integer #全自费患者医技总额
    # field :qzfypj_num, :integer #全自费患者药品总额
    # field :qzfhl_num, :integer #全自费患者护理总额
    # field :qzfgl_num, :integer #全自费患者管理总额
    # field :qzf_avg, :float #全自费患者例均支付总额
    # field :qzfyl_avg, :float #全自费患者例均医疗总额
    # field :qzfyj_avg, :float #全自费患者例均医技总额
    # field :qzfypj_avg, :float #全自费患者例均药品总额
    # field :qzfhl_avg, :float #全自费患者例均护理总额
    # field :qzfgl_avg, :float #全自费患者例均管理总额
    # field :qzf_rate, :float #全自费患者支付总额占比
    # field :qzfyl_rate, :float #全自费患者医疗总额占比
    # field :qzfyj_rate, :float #全自费患者医技总额占比
    # field :qzfypj_rate, :float #全自费患者药品总额占比
    # field :qzfhl_rate, :float #全自费患者护理总额占比
    # field :qzfgl_rate, :float #全自费患者管理总额占比
    # field :qtbx_num, :integer #其他社会保险患者支付总额
    # field :qtbxzf_num, :integer #其他社会保险患者自付总额
    # field :qtbxyl_num, :integer #其他社会保险医疗总额
    # field :qtbxyj_num, :integer #其他社会保险医技总额
    # field :qtbxypj_num, :integer #其他社会保险药品总额
    # field :qtbxhl_num, :integer #其他社会保险护理总额
    # field :qtbxgl_num, :integer #其他社会保险管理总额
    # field :qtbx_avg, :float #其他社会保险患者例均支付总额
    # field :qtbxzf_avg, :float #其他社会保险患者例均自付总额
    # field :qtbxyl_avg, :float #其他社会保险例均医疗总额
    # field :qtbxyj_avg, :float #其他社会保险例均医技总额
    # field :qtbxypj_avg, :float #其他社会保险例均药品总额
    # field :qtbxhl_avg, :float #其他社会保险例均护理总额
    # field :qtbxgl_avg, :float #其他社会保险例均管理总额
    # field :qtbx_rate, :float #其他社会保险患者支付总额占比
    # field :qtbxzf_rate, :float #其他社会保险患者自付总额占比
    # field :qtbxyl_rate, :float #其他社会保险医疗总额占比
    # field :qtbxyj_rate, :float #其他社会保险医技总额占比
    # field :qtbxypj_rate, :float #其他社会保险药品总额占比
    # field :qtbxhl_rate, :float #其他社会保险护理总额占比
    # field :qtbxgl_rate, :float #其他社会保险管理总额占比
    # field :qthz_num, :integer #其他患者支付总额
    # field :qthzzf_num, :integer #其他患者自付总额
    # field :qthzyl_num, :integer #其他患者医疗总额
    # field :qthzyj_num, :integer #其他患者医技总额
    # field :qthzypj_num, :integer #其他患者药品总额
    # field :qthzhl_num, :integer #其他患者护理总额
    # field :qthzgl_num, :integer #其他患者管理总额
    # field :qthz_avg, :float #其他患者例均支付总额
    # field :qthzzf_avg, :float #其他患者例均自付总额
    # field :qthzyl_avg, :float #其他患者例均医疗总额
    # field :qthzyj_avg, :float #其他患者例均医技总额
    # field :qthzypj_avg, :float #其他患者例均药品总额
    # field :qthzhl_avg, :float #其他患者例均护理总额
    # field :qthzgl_avg, :float #其他患者例均管理总额
    # field :qthz_rate, :float #其他患者支付总额占比
    # field :qthzzf_rate, :float #其他患者自付总额占比
    # field :qthzyl_rate, :float #其他患者医疗总额占比
    # field :qthzyj_rate, :float #其他患者医技总额占比
    # field :qthzypj_rate, :float #其他患者药品总额占比
    # field :qthzhl_rate, :float #其他患者护理总额占比
    # field :qthzgl_rate, :float #其他患者管理总额占比
    # field :ssywss_num, :integer #手术中意外损伤
    # field :ssywqg_num, :integer #手术中意外切割
    # field :ssywzc_num, :integer #手术中意外针刺
    # field :ssywck_num, :integer #手术中意外穿孔
    # field :ssywcx_num, :integer #手术中意外出血
    # field :ssylyw_num, :integer #手术中体内遗留异物
    # field :sswjsb_num, :integer #手术中无菌预防措施的失败
    # field :ssczbd_num, :integer #手术中操作不当
    # field :ssywss_rate, :float #手术中意外损伤占比
    # field :ssywqg_rate, :float #手术中意外切割占比
    # field :ssywzc_rate, :float #手术中意外针刺占比
    # field :ssywck_rate, :float #手术中意外穿孔占比
    # field :ssywcx_rate, :float #手术中意外出血占比
    # field :ssylyw_rate, :float #手术中体内遗留异物占比
    # field :sswjsb_rate, :float #手术中无菌预防措施的失败占比
    # field :ssczbd_rate, :float #手术中操作不当
    # field :zlywzl_num, :integer #治疗中意外损伤
    # field :zlywqg_num, :integer #治疗中意外切割
    # field :zlywzc_num, :integer #治疗中意外针刺
    # field :zlywck_num, :integer #治疗中意外穿孔
    # field :zlywcx_num, :integer #治疗中意外出血
    # field :zlylyw_num, :integer #治疗中体内遗留异物
    # field :zlwjsb_num, :integer #治疗中无菌预防措施的失败
    # field :zlczbd_num, :integer #治疗中操作不当
    # field :zlywzl_rate, :float #治疗中意外损伤占比
    # field :zlywqg_rate, :float #治疗中意外切割占比
    # field :zlywzc_rate, :float #治疗中意外针刺占比
    # field :zlywck_rate, :float #治疗中意外穿孔占比
    # field :zlywcx_rate, :float #治疗中意外出血占比
    # field :zlylyw_rate, :float #治疗中体内遗留异物占比
    # field :zlwjsb_rate, :float #治疗中无菌预防措施的失败占比
    # field :zlczbd_rate, :float #治疗中操作不当
    # field :szh_num, :integer #输注后感染
    # field :czh_num, :integer #操作后伤口感染
    # field :ssh_num, :integer #手术后切口感染
    # field :stx_num, :integer #肾透析感染
    # field :rgjt_num, :integer #人工假体植入感染
    # field :ylqj_num, :integer #医疗器具感染
    # field :szh_rate, :float #输注后感染占比
    # field :czh_rate, :float #操作后伤口感染占比
    # field :ssh_rate, :float #手术后切口感染占比
    # field :stx_rate, :float #肾透析感染占比
    # field :rgjt_rate, :float #人工假体植入感染占比
    # field :ylqj_rate, :float #医疗器具感染占比
    # field :ssls_num, :integer #手术例数
    # field :mzzy_num, :integer #门诊住院病历数
    # field :jzzy_num, :integer #急诊住院病历数
    # field :ybzf_num, :integer #本市医保支付病历数
    # field :xnh_num, :integer #本市新农合支付病历数
    # field :qzfbl_num, :integer #全自费病历数
    # field :qgfbl_num, :integer #全公费病历数
    # field :ssls_rate, :float #手术例数占比
    # field :mzzy_rate, :float #门诊住院病历数占比
    # field :jzzy_rate, :float #急诊住院病历数占比
    # field :ybzf_rate, :float #医保支付病历数占比
    # field :xnh_rate, :float #本市新农合支付病历数占比
    # field :qzfbl_rate, :float #全自费病历数占比
    # field :qgfbl_rate, :float #全公费病历数占比
    # field :hos_num, :integer #病例总数
    # field :pc_num, :integer #排除病例数
    # field :wrmdc_num, :integer #未入MDC病例数
    # field :wrz_num, :integer #未入组病例数
    # field :qy_num, :integer #QY病例数
    # field :drg_rate, :float #入组率
    # field :blood_num, :integer #输血总人数
    # field :ablood_num, :integer #A型血型患者总人数
    # field :bblood_num, :integer #B型血型患者总人数
    # field :abblood_num, :integer #AB型血型患者总人数
    # field :oblood_num, :integer #O型血型患者总人数
    # field :wcblood_num, :integer #未查血型患者总人数
    # field :blood_rate, :float #输血人数占比
    # field :ablood_rate, :float #A型血型患者人数占比
    # field :bblood_rate, :float #B型血型患者人数占比
    # field :abblood_rate, :float #AB型血型患者人数占比
    # field :oblood_rate, :float #O型血型患者人数占比
    # field :wcblood_rate, :float #未查血型患者人数占比
    # field :mz_num, :integer #麻醉总人数
    # field :wmz_num, :integer #有手术无麻醉患者总人数
    # field :qsmz_num, :integer #全身麻醉患者总人数
    # field :xrmz_num, :integer #吸入麻醉（气管内插管、喉罩、面罩）患者总人数
    # field :jmmz_num, :integer #静脉麻醉（全凭静脉麻醉）患者总人数
    # field :jcmz_num, :integer #基础麻醉（直肠注入、肌肉注射）患者总人数
    # field :qymz_num, :integer #区域麻醉患者总人数
    # field :zgnmz_num, :integer #椎管内麻醉患者总人数
    # field :mz_rate, :float #麻醉人数占比
    # field :wmz_rate, :float #有手术无麻醉患者总人数占比
    # field :qsmz_rate, :float #全身麻醉患者总人数占比
    # field :xrmz_rate, :float #吸入麻醉（气管内插管、喉罩、面罩）患者总人数占比
    # field :jmmz_rate, :float #静脉麻醉（全凭静脉麻醉）患者总人数占比
    # field :jcmz_rate, :float #基础麻醉（直肠注入、肌肉注射）患者总人数占比
    # field :qymz_rate, :float #区域麻醉患者总人数占比
    # field :zgnmz_rate, :float #椎管内麻醉患者总人数占比
    # field :ymwfh_num, :integer #蛛网膜下-硬膜外复合麻醉患者总人数
    # field :fhmz_num, :integer #复合麻醉患者总人数
    # field :btywfh_num, :integer #不同药物的复合：普鲁卡因静脉复合全麻，神经安定镇痛麻醉等患者总人数
    # field :btfffh_num, :integer #不同方法的复合：静吸复合全麻，针药复合麻醉，全身-硬膜外复合麻醉，脊髓-硬膜外复合麻醉等患者总人数
    # field :tsfffh_num, :integer #特殊方法的复合：全麻复合全身降温（低温麻醉）， 控制性降压等患者总人数
    # field :jxfh_num, :integer #静吸复合麻醉患者总人数
    # field :qtmz_num, :integer #其他麻醉患者总人数
    # field :ymwfh_rate, :float #蛛网膜下-硬膜外复合麻醉患者总人数占比
    # field :fhmz_rate, :float #复合麻醉患者总人数占比
    # field :btywfh_rate, :float #不同药物的复合：普鲁卡因静脉复合全麻，神经安定镇痛麻醉等患者总人数占比
    # field :btfffh_rate, :float #不同方法的复合：静吸复合全麻，针药复合麻醉，全身-硬膜外复合麻醉，脊髓-硬膜外复合麻醉等患者总人数占比
    # field :tsfffh_rate, :float #特殊方法的复合：全麻复合全身降温（低温麻醉）， 控制性降压等患者总人数占比
    # field :jxfh_rate, :float #静吸复合麻醉患者总人数占比
    # field :qtmz_rate, :float #其他麻醉患者总人数占比
    # field :zwmx_num, :integer #蛛网膜下腔阻滞患者总人数
    # field :zwmx_rate, :float #蛛网膜下腔阻滞患者总人数占比
    # field :ymw_num, :integer #硬膜外间隙阻滞（含骶管阻滞）患者总人数
    # field :ymw_rate, :float #硬膜外间隙阻滞（含骶管阻滞）患者总人数占比
    # # field :jc_num, :integer #颈丛阻滞患者总人数
    # # field :jc_rate, :float #颈丛阻滞患者总人数占比
    # field :sj_num, :integer #神经及神经丛阻滞患者总人数
    # field :sj_rate, :float #神经及神经丛阻滞患者总人数占比
    # field :bc_num, :integer #臂丛阻滞及上肢神经阻滞患者总人数
    # field :yz_num, :integer #腰骶神经丛阻滞及下肢神经阻滞患者总人数
    # field :qg_num, :integer #躯干神经阻滞：肋间神经阻滞患者总人数
    # field :zp_num, :integer #椎旁神经阻滞患者总人数
    # field :per_num, :integer #会阴神经阻滞患者总人数
    # field :jg_num, :integer #交感神经阻滞：星状神经节阻滞患者总人数
    # field :xy_num, :integer #胸腰交感神经阻滞患者总人数
    # field :n_num, :integer #脑神经阻滞：三叉神经阻滞、舌咽神经阻滞患者总人数
    # field :bc_rate, :float #臂丛阻滞及上肢神经阻滞患者总人数占比
    # field :yz_rate, :float #腰骶神经丛阻滞及下肢神经阻滞患者总人数占比
    # field :qg_rate, :float #躯干神经阻滞：肋间神经阻滞患者总人数占比
    # field :zp_rate, :float #椎旁神经阻滞患者总人数占比
    # field :per_rate, :float #会阴神经阻滞患者总人数占比
    # field :jg_rate, :float #交感神经阻滞：星状神经节阻滞患者总人数占比
    # field :xy_rate, :float #胸腰交感神经阻滞患者总人数占比
    # field :n_rate, :float #脑神经阻滞：三叉神经阻滞、舌咽神经阻滞患者总人数占比
    # field :baby_num, :integer #新生儿总数
    # field :baby_rate, :float #新生儿总数占比
    # field :boy_num, :integer #新生儿男孩数
    # field :boy_rate, :float #新生儿男孩数占比
    # field :girl_num, :integer #新生儿女孩数
    # field :girl_rate, :float #新生儿女孩数占比
    # field :def_num, :integer #新生儿缺陷总数
    # field :def_rate, :float #新生儿缺陷总数占比
    # field :ck_num, :integer #产科总例数
    # field :ck_rate, :float #产科总例数占比
    # field :pgc_num, :integer #剖宫产例数
    # field :pgc_rate, :float #剖宫产例数占比
    # field :sc_num, :integer #顺产例数
    # field :sc_rate, :float #顺产例数占比
    # field :dt_num, :integer #单胎总例数
    # field :dt_rate, :float #单胎总例数占比
    # field :sbt_num, :integer #双胞胎总例数
    # field :sbt_rate, :float #双胞胎总例数占比
    # field :dbt_num, :integer #多胞胎总例数
    # field :dbt_rate, :float #多胞胎总例数占比
    # field :st_num, :integer #死胎总例数
    # field :st_rate, :float #死胎总例数占比
    # field :xhqx_num, :integer #消化系统缺陷总例数
    # field :sjqx_num, :integer #神经系统缺陷总例数
    # field :hxqx_num, :integer #呼吸系统缺陷总例数
    # field :xyqx_num, :integer #血液循环系统缺陷总例数
    # field :ydqx_num, :integer #运动系统缺陷总例数
    # field :nfmqx_num, :integer #内分泌系统缺陷总例数
    # field :mnqx_num, :integer #泌尿系统缺陷总例数
    # field :szqx_num, :integer #生殖系统缺陷总例数
    # field :xhqx_rate, :float #消化系统缺陷总例数占比
    # field :sjqx_rate, :float #神经系统缺陷总例数占比
    # field :hxqx_rate, :float #呼吸系统缺陷总例数占比
    # field :xyqx_rate, :float #血液循环系统缺陷总例数占比
    # field :ydqx_rate, :float #运动系统缺陷总例数占比
    # field :nfmqx_rate, :float #内分泌系统缺陷总例数占比
    # field :mnqx_rate, :float #泌尿系统缺陷总例数占比
    # field :szqx_rate, :float #生殖系统缺陷总例数占比

    # field :stat_type

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:time, :org, :weight_count, :death_num, :death_rate, :icd10_num, :day_avg, :fee_avg, :fee_index, :day_index, :cmi, :death_age_avg, :weight, :int_time, :num_sum, :death_rate_log, :org_type, :time_type, :true_org])
    |> validate_required([])
  end
end
